// Code generated by ent, DO NOT EDIT.

package doublecomparators

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the doublecomparators type in the database.
	Label = "double_comparators"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGtField holds the string denoting the gt_field field in the database.
	FieldGtField = "gt_field"
	// FieldGteLteField holds the string denoting the gte_lte_field field in the database.
	FieldGteLteField = "gte_lte_field"
	// Table holds the table name of the doublecomparators in the database.
	Table = "double_comparators"
)

// Columns holds all SQL columns for doublecomparators fields.
var Columns = []string{
	FieldID,
	FieldGtField,
	FieldGteLteField,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultGtField holds the default value on creation for the "gt_field" field.
	DefaultGtField float64
	// DefaultGteLteField holds the default value on creation for the "gte_lte_field" field.
	DefaultGteLteField float64
	// GteLteFieldValidator is a validator for the "gte_lte_field" field. It is called by the builders before save.
	GteLteFieldValidator func(float64) error
)

// OrderOption defines the ordering options for the DoubleComparators queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGtField orders the results by the gt_field field.
func ByGtField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGtField, opts...).ToFunc()
}

// ByGteLteField orders the results by the gte_lte_field field.
func ByGteLteField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGteLteField, opts...).ToFunc()
}
