// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ResidualCel is the predicate function for residualcel builders.
type ResidualCel func(*sql.Selector)
