// Code generated by ent, DO NOT EDIT.

package policed

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the policed type in the database.
	Label = "policed"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCelField holds the string denoting the cel_field field in the database.
	FieldCelField = "cel_field"
	// FieldStandardField holds the string denoting the standard_field field in the database.
	FieldStandardField = "standard_field"
	// Table holds the table name of the policed in the database.
	Table = "policeds"
)

// Columns holds all SQL columns for policed fields.
var Columns = []string{
	FieldID,
	FieldCelField,
	FieldStandardField,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/runtime"
var (
	Hooks  [3]ent.Hook
	Policy ent.Policy
	// DefaultCelField holds the default value on creation for the "cel_field" field.
	DefaultCelField string
	// DefaultStandardField holds the default value on creation for the "standard_field" field.
	DefaultStandardField string
	// StandardFieldValidator is a validator for the "standard_field" field. It is called by the builders before save.
	StandardFieldValidator func(string) error
)

// OrderOption defines the ordering options for the Policed queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCelField orders the results by the cel_field field.
func ByCelField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCelField, opts...).ToFunc()
}

// ByStandardField orders the results by the standard_field field.
func ByStandardField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStandardField, opts...).ToFunc()
}
