package entc

import (
	"bytes"
	"strings"
	"testing"

	entload "entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

// TestBuildClaims_AllUnclaimed proves every procedure with no matching
// binding at all comes back "unclaimed" — the starting case a real, freshly
// scaffolded graph with zero entconnect bindings anywhere produces.
func TestBuildClaims_AllUnclaimed(t *testing.T) {
	all := []string{"/pkg.Svc/A", "/pkg.Svc/B"}
	claims := BuildClaims(all, map[string][]Binding{})
	if len(claims) != 2 {
		t.Fatalf("want 2 claims, got %d: %+v", len(claims), claims)
	}
	for _, c := range claims {
		if c.Claimant != "unclaimed" {
			t.Fatalf("want every claimant \"unclaimed\", got %+v", c)
		}
	}
}

// TestBuildClaims_Mixed proves crud:<op>/manual/unclaimed all render
// correctly in one pass, and the returned slice is sorted by procedure
// regardless of the order bindings names its schemas or procedures in.
func TestBuildClaims_Mixed(t *testing.T) {
	all := []string{"/pkg.Svc/A", "/pkg.Svc/B", "/pkg.Svc/C", "/pkg.Svc/D"}
	bindings := map[string][]Binding{
		"Zeta":  {{Op: OpGet, Procedure: "/pkg.Svc/A"}},
		"Alpha": {{Op: OpManual, Procedure: "/pkg.Svc/B"}},
	}
	claims := BuildClaims(all, bindings)
	want := []Claim{
		{Procedure: "/pkg.Svc/A", Claimant: "crud:get"},
		{Procedure: "/pkg.Svc/B", Claimant: "manual"},
		{Procedure: "/pkg.Svc/C", Claimant: "unclaimed"},
		{Procedure: "/pkg.Svc/D", Claimant: "unclaimed"},
	}
	if len(claims) != len(want) {
		t.Fatalf("want %d claims, got %d: %+v", len(want), len(claims), claims)
	}
	for i := range want {
		if claims[i] != want[i] {
			t.Fatalf("claim %d: want %+v, got %+v", i, want[i], claims[i])
		}
	}
}

// TestBuildClaims_Empty proves the zero-procedure case produces a valid,
// header-only report file rather than an absent file.
func TestBuildClaims_Empty(t *testing.T) {
	claims := BuildClaims(nil, map[string][]Binding{})
	if len(claims) != 0 {
		t.Fatalf("want zero claims for a zero-procedure descriptor set, got %d: %+v", len(claims), claims)
	}
	var buf bytes.Buffer
	if err := WriteClaimsReport(&buf, claims); err != nil {
		t.Fatalf("WriteClaimsReport: %v", err)
	}
	got := buf.String()
	if got == "" {
		t.Fatal("want a non-empty header-only report, got an empty file")
	}
	if !strings.HasPrefix(got, "# Code generated by entconnect. DO NOT EDIT.\n") {
		t.Fatalf("want the report to start with the generated-file header, got: %q", got)
	}
	if strings.Count(got, "\n") != 1 {
		t.Fatalf("want exactly one line (the header) for a zero-claim report, got: %q", got)
	}
}

// TestBuildClaims_Stability builds the same claims from bindings supplied
// in five different input orders and asserts the rendered report bytes are
// byte-identical every time (D-20) — run with -count=5 in CI so any
// accidental map-order dependence surfaces as a flake, not a latent bug.
func TestBuildClaims_Stability(t *testing.T) {
	all := []string{"/pkg.Svc/A", "/pkg.Svc/B", "/pkg.Svc/C", "/pkg.Svc/D", "/pkg.Svc/E"}

	orders := []map[string][]Binding{
		{
			"Alpha": {{Op: OpGet, Procedure: "/pkg.Svc/A"}},
			"Beta":  {{Op: OpCreate, Procedure: "/pkg.Svc/B"}},
			"Gamma": {{Op: OpManual, Procedure: "/pkg.Svc/C"}},
			"Delta": {{Op: OpDelete, Procedure: "/pkg.Svc/D"}},
		},
		{
			"Delta": {{Op: OpDelete, Procedure: "/pkg.Svc/D"}},
			"Gamma": {{Op: OpManual, Procedure: "/pkg.Svc/C"}},
			"Beta":  {{Op: OpCreate, Procedure: "/pkg.Svc/B"}},
			"Alpha": {{Op: OpGet, Procedure: "/pkg.Svc/A"}},
		},
		{
			"Gamma": {{Op: OpManual, Procedure: "/pkg.Svc/C"}},
			"Alpha": {{Op: OpGet, Procedure: "/pkg.Svc/A"}},
			"Delta": {{Op: OpDelete, Procedure: "/pkg.Svc/D"}},
			"Beta":  {{Op: OpCreate, Procedure: "/pkg.Svc/B"}},
		},
		{
			"Beta":  {{Op: OpCreate, Procedure: "/pkg.Svc/B"}},
			"Delta": {{Op: OpDelete, Procedure: "/pkg.Svc/D"}},
			"Alpha": {{Op: OpGet, Procedure: "/pkg.Svc/A"}},
			"Gamma": {{Op: OpManual, Procedure: "/pkg.Svc/C"}},
		},
		{
			"Alpha": {{Op: OpGet, Procedure: "/pkg.Svc/A"}},
			"Gamma": {{Op: OpManual, Procedure: "/pkg.Svc/C"}},
			"Delta": {{Op: OpDelete, Procedure: "/pkg.Svc/D"}},
			"Beta":  {{Op: OpCreate, Procedure: "/pkg.Svc/B"}},
		},
	}

	var first string
	for i, bindings := range orders {
		claims := BuildClaims(all, bindings)
		var buf bytes.Buffer
		if err := WriteClaimsReport(&buf, claims); err != nil {
			t.Fatalf("order %d: WriteClaimsReport: %v", i, err)
		}
		got := buf.String()
		if i == 0 {
			first = got
			continue
		}
		if got != first {
			t.Fatalf("order %d produced a different report than order 0:\norder 0: %q\norder %d: %q", i, first, i, got)
		}
	}
}

// TestConflict_DuplicateClaimAndDuplicateOp loads the real negative-build
// fixture (internal/entconnecttest/conflict/ent/schema/{dupe_a,dupe_b}.go)
// via entc.LoadGraph and runs the real entconnect.Generate call path,
// proving both D-05 conflict shapes — a procedure claimed by two schemas,
// and a schema declaring the same Op twice — are collected in ONE pass and
// named in ONE error, never first-offense-wins.
func TestConflict_DuplicateClaimAndDuplicateOp(t *testing.T) {
	graph, err := entload.LoadGraph("../internal/entconnecttest/conflict/ent/schema", &gen.Config{
		Target:  t.TempDir(),
		Package: "github.com/smintz/entconnect/entc/conflict/ent",
	})
	if err != nil {
		t.Fatalf("entc.LoadGraph: %v", err)
	}

	ext, err := NewExtension(WithDescriptorSet(testDescriptorSetPath), WithOutputDir(t.TempDir()))
	if err != nil {
		t.Fatalf("NewExtension: %v", err)
	}

	err = Generate(graph, ext)
	if err == nil {
		t.Fatal("want a non-nil error from the conflict fixtures, got nil")
	}

	msg := err.Error()
	if !strings.Contains(msg, "DupeA") || !strings.Contains(msg, "DupeB") {
		t.Fatalf("want both offending schemas named in the error, got: %s", msg)
	}
	if !strings.Contains(msg, "OrderReadService/GetOrder") {
		t.Fatalf("want the doubly-claimed procedure named in the error, got: %s", msg)
	}
	if !strings.Contains(msg, "PageListService/ListPages") {
		t.Fatalf("want DupeA's second, duplicate-op procedure named in the error, got: %s", msg)
	}
	if !strings.Contains(msg, "duplicate-claim") && !strings.Contains(strings.ToLower(msg), "claimed by") {
		t.Fatalf("want the duplicate-claim conflict described, got: %s", msg)
	}
	if !strings.Contains(msg, "declares get twice") {
		t.Fatalf("want the duplicate-op conflict described, got: %s", msg)
	}
}

// TestConflict_Determinism proves the conflict fixture's rendered error
// text is byte-identical across repeated Generate calls — run with
// -count=5 in CI (D-20/D-24).
func TestConflict_Determinism(t *testing.T) {
	graph, err := entload.LoadGraph("../internal/entconnecttest/conflict/ent/schema", &gen.Config{
		Target:  t.TempDir(),
		Package: "github.com/smintz/entconnect/entc/conflict/ent",
	})
	if err != nil {
		t.Fatalf("entc.LoadGraph: %v", err)
	}
	ext, err := NewExtension(WithDescriptorSet(testDescriptorSetPath), WithOutputDir(t.TempDir()))
	if err != nil {
		t.Fatalf("NewExtension: %v", err)
	}

	first := Generate(graph, ext)
	if first == nil {
		t.Fatal("want a non-nil error, got nil")
	}
	second := Generate(graph, ext)
	if second == nil {
		t.Fatal("want a non-nil error on the second call, got nil")
	}
	if first.Error() != second.Error() {
		t.Fatalf("want byte-identical rendered errors across repeated Generate calls, got:\n%s\n---\n%s", first.Error(), second.Error())
	}
}
