// Code generated by ent, DO NOT EDIT.

package ignorealwayswithcel

import (
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldLTE(FieldID, id))
}

// AlwaysIgnored applies equality check predicate on the "always_ignored" field. It's identical to AlwaysIgnoredEQ.
func AlwaysIgnored(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEQ(FieldAlwaysIgnored, v))
}

// Enforced applies equality check predicate on the "enforced" field. It's identical to EnforcedEQ.
func Enforced(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEQ(FieldEnforced, v))
}

// AlwaysIgnoredEQ applies the EQ predicate on the "always_ignored" field.
func AlwaysIgnoredEQ(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEQ(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredNEQ applies the NEQ predicate on the "always_ignored" field.
func AlwaysIgnoredNEQ(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldNEQ(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredIn applies the In predicate on the "always_ignored" field.
func AlwaysIgnoredIn(vs ...string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldIn(FieldAlwaysIgnored, vs...))
}

// AlwaysIgnoredNotIn applies the NotIn predicate on the "always_ignored" field.
func AlwaysIgnoredNotIn(vs ...string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldNotIn(FieldAlwaysIgnored, vs...))
}

// AlwaysIgnoredGT applies the GT predicate on the "always_ignored" field.
func AlwaysIgnoredGT(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldGT(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredGTE applies the GTE predicate on the "always_ignored" field.
func AlwaysIgnoredGTE(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldGTE(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredLT applies the LT predicate on the "always_ignored" field.
func AlwaysIgnoredLT(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldLT(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredLTE applies the LTE predicate on the "always_ignored" field.
func AlwaysIgnoredLTE(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldLTE(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredContains applies the Contains predicate on the "always_ignored" field.
func AlwaysIgnoredContains(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldContains(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredHasPrefix applies the HasPrefix predicate on the "always_ignored" field.
func AlwaysIgnoredHasPrefix(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldHasPrefix(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredHasSuffix applies the HasSuffix predicate on the "always_ignored" field.
func AlwaysIgnoredHasSuffix(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldHasSuffix(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredEqualFold applies the EqualFold predicate on the "always_ignored" field.
func AlwaysIgnoredEqualFold(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEqualFold(FieldAlwaysIgnored, v))
}

// AlwaysIgnoredContainsFold applies the ContainsFold predicate on the "always_ignored" field.
func AlwaysIgnoredContainsFold(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldContainsFold(FieldAlwaysIgnored, v))
}

// EnforcedEQ applies the EQ predicate on the "enforced" field.
func EnforcedEQ(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEQ(FieldEnforced, v))
}

// EnforcedNEQ applies the NEQ predicate on the "enforced" field.
func EnforcedNEQ(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldNEQ(FieldEnforced, v))
}

// EnforcedIn applies the In predicate on the "enforced" field.
func EnforcedIn(vs ...string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldIn(FieldEnforced, vs...))
}

// EnforcedNotIn applies the NotIn predicate on the "enforced" field.
func EnforcedNotIn(vs ...string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldNotIn(FieldEnforced, vs...))
}

// EnforcedGT applies the GT predicate on the "enforced" field.
func EnforcedGT(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldGT(FieldEnforced, v))
}

// EnforcedGTE applies the GTE predicate on the "enforced" field.
func EnforcedGTE(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldGTE(FieldEnforced, v))
}

// EnforcedLT applies the LT predicate on the "enforced" field.
func EnforcedLT(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldLT(FieldEnforced, v))
}

// EnforcedLTE applies the LTE predicate on the "enforced" field.
func EnforcedLTE(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldLTE(FieldEnforced, v))
}

// EnforcedContains applies the Contains predicate on the "enforced" field.
func EnforcedContains(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldContains(FieldEnforced, v))
}

// EnforcedHasPrefix applies the HasPrefix predicate on the "enforced" field.
func EnforcedHasPrefix(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldHasPrefix(FieldEnforced, v))
}

// EnforcedHasSuffix applies the HasSuffix predicate on the "enforced" field.
func EnforcedHasSuffix(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldHasSuffix(FieldEnforced, v))
}

// EnforcedEqualFold applies the EqualFold predicate on the "enforced" field.
func EnforcedEqualFold(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldEqualFold(FieldEnforced, v))
}

// EnforcedContainsFold applies the ContainsFold predicate on the "enforced" field.
func EnforcedContainsFold(v string) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.FieldContainsFold(FieldEnforced, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IgnoreAlwaysWithCel) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IgnoreAlwaysWithCel) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IgnoreAlwaysWithCel) predicate.IgnoreAlwaysWithCel {
	return predicate.IgnoreAlwaysWithCel(sql.NotPredicates(p))
}
