// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/policed"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/predicate"
)

// PolicedUpdate is the builder for updating Policed entities.
type PolicedUpdate struct {
	config
	hooks    []Hook
	mutation *PolicedMutation
}

// Where appends a list predicates to the PolicedUpdate builder.
func (_u *PolicedUpdate) Where(ps ...predicate.Policed) *PolicedUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCelField sets the "cel_field" field.
func (_u *PolicedUpdate) SetCelField(v string) *PolicedUpdate {
	_u.mutation.SetCelField(v)
	return _u
}

// SetNillableCelField sets the "cel_field" field if the given value is not nil.
func (_u *PolicedUpdate) SetNillableCelField(v *string) *PolicedUpdate {
	if v != nil {
		_u.SetCelField(*v)
	}
	return _u
}

// SetStandardField sets the "standard_field" field.
func (_u *PolicedUpdate) SetStandardField(v string) *PolicedUpdate {
	_u.mutation.SetStandardField(v)
	return _u
}

// SetNillableStandardField sets the "standard_field" field if the given value is not nil.
func (_u *PolicedUpdate) SetNillableStandardField(v *string) *PolicedUpdate {
	if v != nil {
		_u.SetStandardField(*v)
	}
	return _u
}

// Mutation returns the PolicedMutation object of the builder.
func (_u *PolicedUpdate) Mutation() *PolicedMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PolicedUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicedUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PolicedUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicedUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicedUpdate) check() error {
	if v, ok := _u.mutation.StandardField(); ok {
		if err := policed.StandardFieldValidator(v); err != nil {
			return &ValidationError{Name: "standard_field", err: fmt.Errorf(`ent: validator failed for field "Policed.standard_field": %w`, err)}
		}
	}
	return nil
}

func (_u *PolicedUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policed.Table, policed.Columns, sqlgraph.NewFieldSpec(policed.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CelField(); ok {
		_spec.SetField(policed.FieldCelField, field.TypeString, value)
	}
	if value, ok := _u.mutation.StandardField(); ok {
		_spec.SetField(policed.FieldStandardField, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PolicedUpdateOne is the builder for updating a single Policed entity.
type PolicedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PolicedMutation
}

// SetCelField sets the "cel_field" field.
func (_u *PolicedUpdateOne) SetCelField(v string) *PolicedUpdateOne {
	_u.mutation.SetCelField(v)
	return _u
}

// SetNillableCelField sets the "cel_field" field if the given value is not nil.
func (_u *PolicedUpdateOne) SetNillableCelField(v *string) *PolicedUpdateOne {
	if v != nil {
		_u.SetCelField(*v)
	}
	return _u
}

// SetStandardField sets the "standard_field" field.
func (_u *PolicedUpdateOne) SetStandardField(v string) *PolicedUpdateOne {
	_u.mutation.SetStandardField(v)
	return _u
}

// SetNillableStandardField sets the "standard_field" field if the given value is not nil.
func (_u *PolicedUpdateOne) SetNillableStandardField(v *string) *PolicedUpdateOne {
	if v != nil {
		_u.SetStandardField(*v)
	}
	return _u
}

// Mutation returns the PolicedMutation object of the builder.
func (_u *PolicedUpdateOne) Mutation() *PolicedMutation {
	return _u.mutation
}

// Where appends a list predicates to the PolicedUpdate builder.
func (_u *PolicedUpdateOne) Where(ps ...predicate.Policed) *PolicedUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PolicedUpdateOne) Select(field string, fields ...string) *PolicedUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Policed entity.
func (_u *PolicedUpdateOne) Save(ctx context.Context) (*Policed, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicedUpdateOne) SaveX(ctx context.Context) *Policed {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PolicedUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicedUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicedUpdateOne) check() error {
	if v, ok := _u.mutation.StandardField(); ok {
		if err := policed.StandardFieldValidator(v); err != nil {
			return &ValidationError{Name: "standard_field", err: fmt.Errorf(`ent: validator failed for field "Policed.standard_field": %w`, err)}
		}
	}
	return nil
}

func (_u *PolicedUpdateOne) sqlSave(ctx context.Context) (_node *Policed, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policed.Table, policed.Columns, sqlgraph.NewFieldSpec(policed.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Policed.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, policed.FieldID)
		for _, f := range fields {
			if !policed.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != policed.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CelField(); ok {
		_spec.SetField(policed.FieldCelField, field.TypeString, value)
	}
	if value, ok := _u.mutation.StandardField(); ok {
		_spec.SetField(policed.FieldStandardField, field.TypeString, value)
	}
	_node = &Policed{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policed.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
