// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/predicate"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/unpoliced"
)

// UnpolicedDelete is the builder for deleting a Unpoliced entity.
type UnpolicedDelete struct {
	config
	hooks    []Hook
	mutation *UnpolicedMutation
}

// Where appends a list predicates to the UnpolicedDelete builder.
func (_d *UnpolicedDelete) Where(ps ...predicate.Unpoliced) *UnpolicedDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UnpolicedDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UnpolicedDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UnpolicedDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(unpoliced.Table, sqlgraph.NewFieldSpec(unpoliced.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UnpolicedDeleteOne is the builder for deleting a single Unpoliced entity.
type UnpolicedDeleteOne struct {
	_d *UnpolicedDelete
}

// Where appends a list predicates to the UnpolicedDelete builder.
func (_d *UnpolicedDeleteOne) Where(ps ...predicate.Unpoliced) *UnpolicedDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UnpolicedDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{unpoliced.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UnpolicedDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
