// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/unpoliced"
)

// UnpolicedCreate is the builder for creating a Unpoliced entity.
type UnpolicedCreate struct {
	config
	mutation *UnpolicedMutation
	hooks    []Hook
}

// SetCelField sets the "cel_field" field.
func (_c *UnpolicedCreate) SetCelField(v string) *UnpolicedCreate {
	_c.mutation.SetCelField(v)
	return _c
}

// SetNillableCelField sets the "cel_field" field if the given value is not nil.
func (_c *UnpolicedCreate) SetNillableCelField(v *string) *UnpolicedCreate {
	if v != nil {
		_c.SetCelField(*v)
	}
	return _c
}

// SetStandardField sets the "standard_field" field.
func (_c *UnpolicedCreate) SetStandardField(v string) *UnpolicedCreate {
	_c.mutation.SetStandardField(v)
	return _c
}

// SetNillableStandardField sets the "standard_field" field if the given value is not nil.
func (_c *UnpolicedCreate) SetNillableStandardField(v *string) *UnpolicedCreate {
	if v != nil {
		_c.SetStandardField(*v)
	}
	return _c
}

// Mutation returns the UnpolicedMutation object of the builder.
func (_c *UnpolicedCreate) Mutation() *UnpolicedMutation {
	return _c.mutation
}

// Save creates the Unpoliced in the database.
func (_c *UnpolicedCreate) Save(ctx context.Context) (*Unpoliced, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnpolicedCreate) SaveX(ctx context.Context) *Unpoliced {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnpolicedCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnpolicedCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UnpolicedCreate) defaults() error {
	if _, ok := _c.mutation.CelField(); !ok {
		v := unpoliced.DefaultCelField
		_c.mutation.SetCelField(v)
	}
	if _, ok := _c.mutation.StandardField(); !ok {
		v := unpoliced.DefaultStandardField
		_c.mutation.SetStandardField(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnpolicedCreate) check() error {
	if _, ok := _c.mutation.CelField(); !ok {
		return &ValidationError{Name: "cel_field", err: errors.New(`ent: missing required field "Unpoliced.cel_field"`)}
	}
	if _, ok := _c.mutation.StandardField(); !ok {
		return &ValidationError{Name: "standard_field", err: errors.New(`ent: missing required field "Unpoliced.standard_field"`)}
	}
	if v, ok := _c.mutation.StandardField(); ok {
		if err := unpoliced.StandardFieldValidator(v); err != nil {
			return &ValidationError{Name: "standard_field", err: fmt.Errorf(`ent: validator failed for field "Unpoliced.standard_field": %w`, err)}
		}
	}
	return nil
}

func (_c *UnpolicedCreate) sqlSave(ctx context.Context) (*Unpoliced, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnpolicedCreate) createSpec() (*Unpoliced, *sqlgraph.CreateSpec) {
	var (
		_node = &Unpoliced{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unpoliced.Table, sqlgraph.NewFieldSpec(unpoliced.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CelField(); ok {
		_spec.SetField(unpoliced.FieldCelField, field.TypeString, value)
		_node.CelField = value
	}
	if value, ok := _c.mutation.StandardField(); ok {
		_spec.SetField(unpoliced.FieldStandardField, field.TypeString, value)
		_node.StandardField = value
	}
	return _node, _spec
}

// UnpolicedCreateBulk is the builder for creating many Unpoliced entities in bulk.
type UnpolicedCreateBulk struct {
	config
	err      error
	builders []*UnpolicedCreate
}

// Save creates the Unpoliced entities in the database.
func (_c *UnpolicedCreateBulk) Save(ctx context.Context) ([]*Unpoliced, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Unpoliced, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnpolicedMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnpolicedCreateBulk) SaveX(ctx context.Context) []*Unpoliced {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnpolicedCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnpolicedCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
