// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/predicate"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/unpoliced"
)

// UnpolicedUpdate is the builder for updating Unpoliced entities.
type UnpolicedUpdate struct {
	config
	hooks    []Hook
	mutation *UnpolicedMutation
}

// Where appends a list predicates to the UnpolicedUpdate builder.
func (_u *UnpolicedUpdate) Where(ps ...predicate.Unpoliced) *UnpolicedUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCelField sets the "cel_field" field.
func (_u *UnpolicedUpdate) SetCelField(v string) *UnpolicedUpdate {
	_u.mutation.SetCelField(v)
	return _u
}

// SetNillableCelField sets the "cel_field" field if the given value is not nil.
func (_u *UnpolicedUpdate) SetNillableCelField(v *string) *UnpolicedUpdate {
	if v != nil {
		_u.SetCelField(*v)
	}
	return _u
}

// SetStandardField sets the "standard_field" field.
func (_u *UnpolicedUpdate) SetStandardField(v string) *UnpolicedUpdate {
	_u.mutation.SetStandardField(v)
	return _u
}

// SetNillableStandardField sets the "standard_field" field if the given value is not nil.
func (_u *UnpolicedUpdate) SetNillableStandardField(v *string) *UnpolicedUpdate {
	if v != nil {
		_u.SetStandardField(*v)
	}
	return _u
}

// Mutation returns the UnpolicedMutation object of the builder.
func (_u *UnpolicedUpdate) Mutation() *UnpolicedMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UnpolicedUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnpolicedUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UnpolicedUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnpolicedUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnpolicedUpdate) check() error {
	if v, ok := _u.mutation.StandardField(); ok {
		if err := unpoliced.StandardFieldValidator(v); err != nil {
			return &ValidationError{Name: "standard_field", err: fmt.Errorf(`ent: validator failed for field "Unpoliced.standard_field": %w`, err)}
		}
	}
	return nil
}

func (_u *UnpolicedUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unpoliced.Table, unpoliced.Columns, sqlgraph.NewFieldSpec(unpoliced.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CelField(); ok {
		_spec.SetField(unpoliced.FieldCelField, field.TypeString, value)
	}
	if value, ok := _u.mutation.StandardField(); ok {
		_spec.SetField(unpoliced.FieldStandardField, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unpoliced.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UnpolicedUpdateOne is the builder for updating a single Unpoliced entity.
type UnpolicedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UnpolicedMutation
}

// SetCelField sets the "cel_field" field.
func (_u *UnpolicedUpdateOne) SetCelField(v string) *UnpolicedUpdateOne {
	_u.mutation.SetCelField(v)
	return _u
}

// SetNillableCelField sets the "cel_field" field if the given value is not nil.
func (_u *UnpolicedUpdateOne) SetNillableCelField(v *string) *UnpolicedUpdateOne {
	if v != nil {
		_u.SetCelField(*v)
	}
	return _u
}

// SetStandardField sets the "standard_field" field.
func (_u *UnpolicedUpdateOne) SetStandardField(v string) *UnpolicedUpdateOne {
	_u.mutation.SetStandardField(v)
	return _u
}

// SetNillableStandardField sets the "standard_field" field if the given value is not nil.
func (_u *UnpolicedUpdateOne) SetNillableStandardField(v *string) *UnpolicedUpdateOne {
	if v != nil {
		_u.SetStandardField(*v)
	}
	return _u
}

// Mutation returns the UnpolicedMutation object of the builder.
func (_u *UnpolicedUpdateOne) Mutation() *UnpolicedMutation {
	return _u.mutation
}

// Where appends a list predicates to the UnpolicedUpdate builder.
func (_u *UnpolicedUpdateOne) Where(ps ...predicate.Unpoliced) *UnpolicedUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UnpolicedUpdateOne) Select(field string, fields ...string) *UnpolicedUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Unpoliced entity.
func (_u *UnpolicedUpdateOne) Save(ctx context.Context) (*Unpoliced, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnpolicedUpdateOne) SaveX(ctx context.Context) *Unpoliced {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UnpolicedUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnpolicedUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnpolicedUpdateOne) check() error {
	if v, ok := _u.mutation.StandardField(); ok {
		if err := unpoliced.StandardFieldValidator(v); err != nil {
			return &ValidationError{Name: "standard_field", err: fmt.Errorf(`ent: validator failed for field "Unpoliced.standard_field": %w`, err)}
		}
	}
	return nil
}

func (_u *UnpolicedUpdateOne) sqlSave(ctx context.Context) (_node *Unpoliced, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unpoliced.Table, unpoliced.Columns, sqlgraph.NewFieldSpec(unpoliced.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Unpoliced.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unpoliced.FieldID)
		for _, f := range fields {
			if !unpoliced.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != unpoliced.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CelField(); ok {
		_spec.SetField(unpoliced.FieldCelField, field.TypeString, value)
	}
	if value, ok := _u.mutation.StandardField(); ok {
		_spec.SetField(unpoliced.FieldStandardField, field.TypeString, value)
	}
	_node = &Unpoliced{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unpoliced.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
