// Code generated by ent, DO NOT EDIT.

package int32comparators

import (
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldID, id))
}

// GtField applies equality check predicate on the "gt_field" field. It's identical to GtFieldEQ.
func GtField(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldGtField, v))
}

// GteField applies equality check predicate on the "gte_field" field. It's identical to GteFieldEQ.
func GteField(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldGteField, v))
}

// LtField applies equality check predicate on the "lt_field" field. It's identical to LtFieldEQ.
func LtField(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldLtField, v))
}

// LteField applies equality check predicate on the "lte_field" field. It's identical to LteFieldEQ.
func LteField(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldLteField, v))
}

// PositiveField applies equality check predicate on the "positive_field" field. It's identical to PositiveFieldEQ.
func PositiveField(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldPositiveField, v))
}

// RangeField applies equality check predicate on the "range_field" field. It's identical to RangeFieldEQ.
func RangeField(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldRangeField, v))
}

// NoRulesField applies equality check predicate on the "no_rules_field" field. It's identical to NoRulesFieldEQ.
func NoRulesField(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldNoRulesField, v))
}

// GtFieldEQ applies the EQ predicate on the "gt_field" field.
func GtFieldEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldGtField, v))
}

// GtFieldNEQ applies the NEQ predicate on the "gt_field" field.
func GtFieldNEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldGtField, v))
}

// GtFieldIn applies the In predicate on the "gt_field" field.
func GtFieldIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldGtField, vs...))
}

// GtFieldNotIn applies the NotIn predicate on the "gt_field" field.
func GtFieldNotIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldGtField, vs...))
}

// GtFieldGT applies the GT predicate on the "gt_field" field.
func GtFieldGT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldGtField, v))
}

// GtFieldGTE applies the GTE predicate on the "gt_field" field.
func GtFieldGTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldGtField, v))
}

// GtFieldLT applies the LT predicate on the "gt_field" field.
func GtFieldLT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldGtField, v))
}

// GtFieldLTE applies the LTE predicate on the "gt_field" field.
func GtFieldLTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldGtField, v))
}

// GteFieldEQ applies the EQ predicate on the "gte_field" field.
func GteFieldEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldGteField, v))
}

// GteFieldNEQ applies the NEQ predicate on the "gte_field" field.
func GteFieldNEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldGteField, v))
}

// GteFieldIn applies the In predicate on the "gte_field" field.
func GteFieldIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldGteField, vs...))
}

// GteFieldNotIn applies the NotIn predicate on the "gte_field" field.
func GteFieldNotIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldGteField, vs...))
}

// GteFieldGT applies the GT predicate on the "gte_field" field.
func GteFieldGT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldGteField, v))
}

// GteFieldGTE applies the GTE predicate on the "gte_field" field.
func GteFieldGTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldGteField, v))
}

// GteFieldLT applies the LT predicate on the "gte_field" field.
func GteFieldLT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldGteField, v))
}

// GteFieldLTE applies the LTE predicate on the "gte_field" field.
func GteFieldLTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldGteField, v))
}

// LtFieldEQ applies the EQ predicate on the "lt_field" field.
func LtFieldEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldLtField, v))
}

// LtFieldNEQ applies the NEQ predicate on the "lt_field" field.
func LtFieldNEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldLtField, v))
}

// LtFieldIn applies the In predicate on the "lt_field" field.
func LtFieldIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldLtField, vs...))
}

// LtFieldNotIn applies the NotIn predicate on the "lt_field" field.
func LtFieldNotIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldLtField, vs...))
}

// LtFieldGT applies the GT predicate on the "lt_field" field.
func LtFieldGT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldLtField, v))
}

// LtFieldGTE applies the GTE predicate on the "lt_field" field.
func LtFieldGTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldLtField, v))
}

// LtFieldLT applies the LT predicate on the "lt_field" field.
func LtFieldLT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldLtField, v))
}

// LtFieldLTE applies the LTE predicate on the "lt_field" field.
func LtFieldLTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldLtField, v))
}

// LteFieldEQ applies the EQ predicate on the "lte_field" field.
func LteFieldEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldLteField, v))
}

// LteFieldNEQ applies the NEQ predicate on the "lte_field" field.
func LteFieldNEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldLteField, v))
}

// LteFieldIn applies the In predicate on the "lte_field" field.
func LteFieldIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldLteField, vs...))
}

// LteFieldNotIn applies the NotIn predicate on the "lte_field" field.
func LteFieldNotIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldLteField, vs...))
}

// LteFieldGT applies the GT predicate on the "lte_field" field.
func LteFieldGT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldLteField, v))
}

// LteFieldGTE applies the GTE predicate on the "lte_field" field.
func LteFieldGTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldLteField, v))
}

// LteFieldLT applies the LT predicate on the "lte_field" field.
func LteFieldLT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldLteField, v))
}

// LteFieldLTE applies the LTE predicate on the "lte_field" field.
func LteFieldLTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldLteField, v))
}

// PositiveFieldEQ applies the EQ predicate on the "positive_field" field.
func PositiveFieldEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldPositiveField, v))
}

// PositiveFieldNEQ applies the NEQ predicate on the "positive_field" field.
func PositiveFieldNEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldPositiveField, v))
}

// PositiveFieldIn applies the In predicate on the "positive_field" field.
func PositiveFieldIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldPositiveField, vs...))
}

// PositiveFieldNotIn applies the NotIn predicate on the "positive_field" field.
func PositiveFieldNotIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldPositiveField, vs...))
}

// PositiveFieldGT applies the GT predicate on the "positive_field" field.
func PositiveFieldGT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldPositiveField, v))
}

// PositiveFieldGTE applies the GTE predicate on the "positive_field" field.
func PositiveFieldGTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldPositiveField, v))
}

// PositiveFieldLT applies the LT predicate on the "positive_field" field.
func PositiveFieldLT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldPositiveField, v))
}

// PositiveFieldLTE applies the LTE predicate on the "positive_field" field.
func PositiveFieldLTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldPositiveField, v))
}

// RangeFieldEQ applies the EQ predicate on the "range_field" field.
func RangeFieldEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldRangeField, v))
}

// RangeFieldNEQ applies the NEQ predicate on the "range_field" field.
func RangeFieldNEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldRangeField, v))
}

// RangeFieldIn applies the In predicate on the "range_field" field.
func RangeFieldIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldRangeField, vs...))
}

// RangeFieldNotIn applies the NotIn predicate on the "range_field" field.
func RangeFieldNotIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldRangeField, vs...))
}

// RangeFieldGT applies the GT predicate on the "range_field" field.
func RangeFieldGT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldRangeField, v))
}

// RangeFieldGTE applies the GTE predicate on the "range_field" field.
func RangeFieldGTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldRangeField, v))
}

// RangeFieldLT applies the LT predicate on the "range_field" field.
func RangeFieldLT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldRangeField, v))
}

// RangeFieldLTE applies the LTE predicate on the "range_field" field.
func RangeFieldLTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldRangeField, v))
}

// NoRulesFieldEQ applies the EQ predicate on the "no_rules_field" field.
func NoRulesFieldEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldEQ(FieldNoRulesField, v))
}

// NoRulesFieldNEQ applies the NEQ predicate on the "no_rules_field" field.
func NoRulesFieldNEQ(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNEQ(FieldNoRulesField, v))
}

// NoRulesFieldIn applies the In predicate on the "no_rules_field" field.
func NoRulesFieldIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldIn(FieldNoRulesField, vs...))
}

// NoRulesFieldNotIn applies the NotIn predicate on the "no_rules_field" field.
func NoRulesFieldNotIn(vs ...int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldNotIn(FieldNoRulesField, vs...))
}

// NoRulesFieldGT applies the GT predicate on the "no_rules_field" field.
func NoRulesFieldGT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGT(FieldNoRulesField, v))
}

// NoRulesFieldGTE applies the GTE predicate on the "no_rules_field" field.
func NoRulesFieldGTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldGTE(FieldNoRulesField, v))
}

// NoRulesFieldLT applies the LT predicate on the "no_rules_field" field.
func NoRulesFieldLT(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLT(FieldNoRulesField, v))
}

// NoRulesFieldLTE applies the LTE predicate on the "no_rules_field" field.
func NoRulesFieldLTE(v int32) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.FieldLTE(FieldNoRulesField, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Int32Comparators) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Int32Comparators) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Int32Comparators) predicate.Int32Comparators {
	return predicate.Int32Comparators(sql.NotPredicates(p))
}
