// Code generated by entconnect. DO NOT EDIT.

package entconnect

import (
	"context"
	"fmt"
	"strconv"

	"connectrpc.com/connect"
	"github.com/smintz/entconnect/internal/entconnecttest/read/ent"
	"github.com/smintz/entconnect/internal/gen/entconnecttestv1"
	"github.com/smintz/entconnect/internal/gen/entconnecttestv1/entconnecttestv1connect"
	entconnectruntime "github.com/smintz/entconnect/runtime"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// orderReadServiceServer implements entconnecttestv1connect.OrderReadServiceHandler
// against a real *ent.Client. Constructed only inside NewServer
// (server.entconnect.go, combining every service this graph binds) —
// application code never receives one directly, and this type exposes
// no accessor of any kind to the *ent.Client it holds (CRUD-07/D-12).
type orderReadServiceServer struct {
	client *ent.Client
}

var _ entconnecttestv1connect.OrderReadServiceHandler = (*orderReadServiceServer)(nil)

func (s *orderReadServiceServer) GetOrder(ctx context.Context, req *connect.Request[entconnecttestv1.GetOrderRequest]) (*connect.Response[entconnecttestv1.GetOrderResponse], error) {
	parsedID, err := strconv.ParseInt(req.Msg.GetId(), 10, 64)
	if err != nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("invalid id: %w", err))
	}
	id := int(parsedID)
	row, err := s.client.Order.Get(ctx, id)
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			return nil, connect.NewError(connect.CodeNotFound, err)
		case ent.IsConstraintError(err):
			return nil, connect.NewError(connect.CodeAlreadyExists, err)
		case ent.IsValidationError(err):
			return nil, connect.NewError(connect.CodeInvalidArgument, err)
		default:
			return nil, entconnectruntime.MapError(err)
		}
	}
	resp := &entconnecttestv1.GetOrderResponse{
		Order: &entconnecttestv1.Order{
			Id:        fmt.Sprint(row.ID),
			Customer:  row.Customer,
			Status:    row.Status,
			CreatedAt: timestamppb.New(row.CreatedAt),
		},
	}
	return connect.NewResponse(resp), nil
}
