// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/smintz/entconnect/internal/entconnecttest/manual/ent/admin"
	"github.com/smintz/entconnect/internal/entconnecttest/manual/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminMixin := schema.Admin{}.Mixin()
	adminMixinFields0 := adminMixin[0].Fields()
	_ = adminMixinFields0
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescName is the schema descriptor for name field.
	adminDescName := adminMixinFields0[0].Descriptor()
	// admin.DefaultName holds the default value on creation for the name field.
	admin.DefaultName = adminDescName.Default.(string)
}
