// Code generated by ent, DO NOT EDIT.

package int32overflow

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the int32overflow type in the database.
	Label = "int32overflow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGtMaxField holds the string denoting the gt_max_field field in the database.
	FieldGtMaxField = "gt_max_field"
	// FieldLtMinField holds the string denoting the lt_min_field field in the database.
	FieldLtMinField = "lt_min_field"
	// Table holds the table name of the int32overflow in the database.
	Table = "int32overflows"
)

// Columns holds all SQL columns for int32overflow fields.
var Columns = []string{
	FieldID,
	FieldGtMaxField,
	FieldLtMinField,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultGtMaxField holds the default value on creation for the "gt_max_field" field.
	DefaultGtMaxField int32
	// DefaultLtMinField holds the default value on creation for the "lt_min_field" field.
	DefaultLtMinField int32
)

// OrderOption defines the ordering options for the Int32Overflow queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGtMaxField orders the results by the gt_max_field field.
func ByGtMaxField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGtMaxField, opts...).ToFunc()
}

// ByLtMinField orders the results by the lt_min_field field.
func ByLtMinField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLtMinField, opts...).ToFunc()
}
