// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/internal/entconnecttest/update/ent/patch"
)

// PatchCreate is the builder for creating a Patch entity.
type PatchCreate struct {
	config
	mutation *PatchMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *PatchCreate) SetTitle(v string) *PatchCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *PatchCreate) SetNillableTitle(v *string) *PatchCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *PatchCreate) SetBody(v string) *PatchCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *PatchCreate) SetNillableBody(v *string) *PatchCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *PatchCreate) SetRevision(v int32) *PatchCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *PatchCreate) SetNillableRevision(v *int32) *PatchCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// Mutation returns the PatchMutation object of the builder.
func (_c *PatchCreate) Mutation() *PatchMutation {
	return _c.mutation
}

// Save creates the Patch in the database.
func (_c *PatchCreate) Save(ctx context.Context) (*Patch, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PatchCreate) SaveX(ctx context.Context) *Patch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PatchCreate) defaults() error {
	if _, ok := _c.mutation.Title(); !ok {
		v := patch.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Body(); !ok {
		v := patch.DefaultBody
		_c.mutation.SetBody(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := patch.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PatchCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Patch.title"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Patch.body"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "Patch.revision"`)}
	}
	return nil
}

func (_c *PatchCreate) sqlSave(ctx context.Context) (*Patch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PatchCreate) createSpec() (*Patch, *sqlgraph.CreateSpec) {
	var (
		_node = &Patch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(patch.Table, sqlgraph.NewFieldSpec(patch.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(patch.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(patch.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(patch.FieldRevision, field.TypeInt32, value)
		_node.Revision = value
	}
	return _node, _spec
}

// PatchCreateBulk is the builder for creating many Patch entities in bulk.
type PatchCreateBulk struct {
	config
	err      error
	builders []*PatchCreate
}

// Save creates the Patch entities in the database.
func (_c *PatchCreateBulk) Save(ctx context.Context) ([]*Patch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Patch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PatchCreateBulk) SaveX(ctx context.Context) []*Patch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
