// Code generated by ent, DO NOT EDIT.

package stringformatwithsibling

import (
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldLTE(FieldID, id))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEQ(FieldEndpoint, v))
}

// Owner applies equality check predicate on the "owner" field. It's identical to OwnerEQ.
func Owner(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEQ(FieldOwner, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldContainsFold(FieldEndpoint, v))
}

// OwnerEQ applies the EQ predicate on the "owner" field.
func OwnerEQ(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEQ(FieldOwner, v))
}

// OwnerNEQ applies the NEQ predicate on the "owner" field.
func OwnerNEQ(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldNEQ(FieldOwner, v))
}

// OwnerIn applies the In predicate on the "owner" field.
func OwnerIn(vs ...string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldIn(FieldOwner, vs...))
}

// OwnerNotIn applies the NotIn predicate on the "owner" field.
func OwnerNotIn(vs ...string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldNotIn(FieldOwner, vs...))
}

// OwnerGT applies the GT predicate on the "owner" field.
func OwnerGT(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldGT(FieldOwner, v))
}

// OwnerGTE applies the GTE predicate on the "owner" field.
func OwnerGTE(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldGTE(FieldOwner, v))
}

// OwnerLT applies the LT predicate on the "owner" field.
func OwnerLT(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldLT(FieldOwner, v))
}

// OwnerLTE applies the LTE predicate on the "owner" field.
func OwnerLTE(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldLTE(FieldOwner, v))
}

// OwnerContains applies the Contains predicate on the "owner" field.
func OwnerContains(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldContains(FieldOwner, v))
}

// OwnerHasPrefix applies the HasPrefix predicate on the "owner" field.
func OwnerHasPrefix(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldHasPrefix(FieldOwner, v))
}

// OwnerHasSuffix applies the HasSuffix predicate on the "owner" field.
func OwnerHasSuffix(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldHasSuffix(FieldOwner, v))
}

// OwnerEqualFold applies the EqualFold predicate on the "owner" field.
func OwnerEqualFold(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldEqualFold(FieldOwner, v))
}

// OwnerContainsFold applies the ContainsFold predicate on the "owner" field.
func OwnerContainsFold(v string) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.FieldContainsFold(FieldOwner, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StringFormatWithSibling) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StringFormatWithSibling) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StringFormatWithSibling) predicate.StringFormatWithSibling {
	return predicate.StringFormatWithSibling(sql.NotPredicates(p))
}
