// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/smintz/entconnect/internal/entconnecttest/read/ent/order"
	"github.com/smintz/entconnect/internal/entconnecttest/read/ent/schema"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderMixin := schema.Order{}.Mixin()
	order.Policy = privacy.NewPolicies(schema.Order{})
	order.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := order.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCustomer is the schema descriptor for customer field.
	orderDescCustomer := orderMixinFields0[0].Descriptor()
	// order.DefaultCustomer holds the default value on creation for the customer field.
	order.DefaultCustomer = orderDescCustomer.Default.(string)
	// order.CustomerValidator is a validator for the "customer" field. It is called by the builders before save.
	order.CustomerValidator = orderDescCustomer.Validators[0].(func(string) error)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderMixinFields0[1].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(string)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
