// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MessageRulesColumns holds the columns for the "message_rules" table.
	MessageRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "lo", Type: field.TypeInt32, Default: 0},
		{Name: "hi", Type: field.TypeInt32, Default: 0},
	}
	// MessageRulesTable holds the schema information for the "message_rules" table.
	MessageRulesTable = &schema.Table{
		Name:       "message_rules",
		Columns:    MessageRulesColumns,
		PrimaryKey: []*schema.Column{MessageRulesColumns[0]},
	}
	// MixedFieldRulesColumns holds the columns for the "mixed_field_rules" table.
	MixedFieldRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "both", Type: field.TypeString, Default: ""},
		{Name: "standard_only", Type: field.TypeString, Default: ""},
		{Name: "cel_only", Type: field.TypeString, Default: ""},
	}
	// MixedFieldRulesTable holds the schema information for the "mixed_field_rules" table.
	MixedFieldRulesTable = &schema.Table{
		Name:       "mixed_field_rules",
		Columns:    MixedFieldRulesColumns,
		PrimaryKey: []*schema.Column{MixedFieldRulesColumns[0]},
	}
	// ResidualCelsColumns holds the columns for the "residual_cels" table.
	ResidualCelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "value", Type: field.TypeString, Default: ""},
	}
	// ResidualCelsTable holds the schema information for the "residual_cels" table.
	ResidualCelsTable = &schema.Table{
		Name:       "residual_cels",
		Columns:    ResidualCelsColumns,
		PrimaryKey: []*schema.Column{ResidualCelsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MessageRulesTable,
		MixedFieldRulesTable,
		ResidualCelsTable,
	}
)

func init() {
}
