// Code generated by ent, DO NOT EDIT.

package requiredoptionalnonstring

import (
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldLTE(FieldID, id))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldEQ(FieldValue, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int32) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.FieldLTE(FieldValue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequiredOptionalNonString) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequiredOptionalNonString) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequiredOptionalNonString) predicate.RequiredOptionalNonString {
	return predicate.RequiredOptionalNonString(sql.NotPredicates(p))
}
