// Code generated by ent, DO NOT EDIT.

package requiredoptionalbytes

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the requiredoptionalbytes type in the database.
	Label = "required_optional_bytes"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// Table holds the table name of the requiredoptionalbytes in the database.
	Table = "required_optional_bytes"
)

// Columns holds all SQL columns for requiredoptionalbytes fields.
var Columns = []string{
	FieldID,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/runtime"
var (
	Hooks [1]ent.Hook
)

// OrderOption defines the ordering options for the RequiredOptionalBytes queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
