// Code generated by ent, DO NOT EDIT.

package stringcodepointbounds

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the stringcodepointbounds type in the database.
	Label = "string_code_point_bounds"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMinLenField holds the string denoting the min_len_field field in the database.
	FieldMinLenField = "min_len_field"
	// FieldMaxLenField holds the string denoting the max_len_field field in the database.
	FieldMaxLenField = "max_len_field"
	// FieldLenField holds the string denoting the len_field field in the database.
	FieldLenField = "len_field"
	// Table holds the table name of the stringcodepointbounds in the database.
	Table = "string_code_point_bounds"
)

// Columns holds all SQL columns for stringcodepointbounds fields.
var Columns = []string{
	FieldID,
	FieldMinLenField,
	FieldMaxLenField,
	FieldLenField,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultMinLenField holds the default value on creation for the "min_len_field" field.
	DefaultMinLenField string
	// MinLenFieldValidator is a validator for the "min_len_field" field. It is called by the builders before save.
	MinLenFieldValidator func(string) error
	// DefaultMaxLenField holds the default value on creation for the "max_len_field" field.
	DefaultMaxLenField string
	// MaxLenFieldValidator is a validator for the "max_len_field" field. It is called by the builders before save.
	MaxLenFieldValidator func(string) error
	// DefaultLenField holds the default value on creation for the "len_field" field.
	DefaultLenField string
	// LenFieldValidator is a validator for the "len_field" field. It is called by the builders before save.
	LenFieldValidator func(string) error
)

// OrderOption defines the ordering options for the StringCodePointBounds queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMinLenField orders the results by the min_len_field field.
func ByMinLenField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinLenField, opts...).ToFunc()
}

// ByMaxLenField orders the results by the max_len_field field.
func ByMaxLenField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxLenField, opts...).ToFunc()
}

// ByLenField orders the results by the len_field field.
func ByLenField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLenField, opts...).ToFunc()
}
