// Code generated by ent, DO NOT EDIT.

package stringcodepointbounds

import (
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLTE(FieldID, id))
}

// MinLenField applies equality check predicate on the "min_len_field" field. It's identical to MinLenFieldEQ.
func MinLenField(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldMinLenField, v))
}

// MaxLenField applies equality check predicate on the "max_len_field" field. It's identical to MaxLenFieldEQ.
func MaxLenField(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldMaxLenField, v))
}

// LenField applies equality check predicate on the "len_field" field. It's identical to LenFieldEQ.
func LenField(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldLenField, v))
}

// MinLenFieldEQ applies the EQ predicate on the "min_len_field" field.
func MinLenFieldEQ(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldMinLenField, v))
}

// MinLenFieldNEQ applies the NEQ predicate on the "min_len_field" field.
func MinLenFieldNEQ(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNEQ(FieldMinLenField, v))
}

// MinLenFieldIn applies the In predicate on the "min_len_field" field.
func MinLenFieldIn(vs ...string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldIn(FieldMinLenField, vs...))
}

// MinLenFieldNotIn applies the NotIn predicate on the "min_len_field" field.
func MinLenFieldNotIn(vs ...string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNotIn(FieldMinLenField, vs...))
}

// MinLenFieldGT applies the GT predicate on the "min_len_field" field.
func MinLenFieldGT(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGT(FieldMinLenField, v))
}

// MinLenFieldGTE applies the GTE predicate on the "min_len_field" field.
func MinLenFieldGTE(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGTE(FieldMinLenField, v))
}

// MinLenFieldLT applies the LT predicate on the "min_len_field" field.
func MinLenFieldLT(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLT(FieldMinLenField, v))
}

// MinLenFieldLTE applies the LTE predicate on the "min_len_field" field.
func MinLenFieldLTE(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLTE(FieldMinLenField, v))
}

// MinLenFieldContains applies the Contains predicate on the "min_len_field" field.
func MinLenFieldContains(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldContains(FieldMinLenField, v))
}

// MinLenFieldHasPrefix applies the HasPrefix predicate on the "min_len_field" field.
func MinLenFieldHasPrefix(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldHasPrefix(FieldMinLenField, v))
}

// MinLenFieldHasSuffix applies the HasSuffix predicate on the "min_len_field" field.
func MinLenFieldHasSuffix(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldHasSuffix(FieldMinLenField, v))
}

// MinLenFieldEqualFold applies the EqualFold predicate on the "min_len_field" field.
func MinLenFieldEqualFold(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEqualFold(FieldMinLenField, v))
}

// MinLenFieldContainsFold applies the ContainsFold predicate on the "min_len_field" field.
func MinLenFieldContainsFold(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldContainsFold(FieldMinLenField, v))
}

// MaxLenFieldEQ applies the EQ predicate on the "max_len_field" field.
func MaxLenFieldEQ(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldMaxLenField, v))
}

// MaxLenFieldNEQ applies the NEQ predicate on the "max_len_field" field.
func MaxLenFieldNEQ(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNEQ(FieldMaxLenField, v))
}

// MaxLenFieldIn applies the In predicate on the "max_len_field" field.
func MaxLenFieldIn(vs ...string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldIn(FieldMaxLenField, vs...))
}

// MaxLenFieldNotIn applies the NotIn predicate on the "max_len_field" field.
func MaxLenFieldNotIn(vs ...string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNotIn(FieldMaxLenField, vs...))
}

// MaxLenFieldGT applies the GT predicate on the "max_len_field" field.
func MaxLenFieldGT(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGT(FieldMaxLenField, v))
}

// MaxLenFieldGTE applies the GTE predicate on the "max_len_field" field.
func MaxLenFieldGTE(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGTE(FieldMaxLenField, v))
}

// MaxLenFieldLT applies the LT predicate on the "max_len_field" field.
func MaxLenFieldLT(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLT(FieldMaxLenField, v))
}

// MaxLenFieldLTE applies the LTE predicate on the "max_len_field" field.
func MaxLenFieldLTE(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLTE(FieldMaxLenField, v))
}

// MaxLenFieldContains applies the Contains predicate on the "max_len_field" field.
func MaxLenFieldContains(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldContains(FieldMaxLenField, v))
}

// MaxLenFieldHasPrefix applies the HasPrefix predicate on the "max_len_field" field.
func MaxLenFieldHasPrefix(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldHasPrefix(FieldMaxLenField, v))
}

// MaxLenFieldHasSuffix applies the HasSuffix predicate on the "max_len_field" field.
func MaxLenFieldHasSuffix(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldHasSuffix(FieldMaxLenField, v))
}

// MaxLenFieldEqualFold applies the EqualFold predicate on the "max_len_field" field.
func MaxLenFieldEqualFold(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEqualFold(FieldMaxLenField, v))
}

// MaxLenFieldContainsFold applies the ContainsFold predicate on the "max_len_field" field.
func MaxLenFieldContainsFold(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldContainsFold(FieldMaxLenField, v))
}

// LenFieldEQ applies the EQ predicate on the "len_field" field.
func LenFieldEQ(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEQ(FieldLenField, v))
}

// LenFieldNEQ applies the NEQ predicate on the "len_field" field.
func LenFieldNEQ(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNEQ(FieldLenField, v))
}

// LenFieldIn applies the In predicate on the "len_field" field.
func LenFieldIn(vs ...string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldIn(FieldLenField, vs...))
}

// LenFieldNotIn applies the NotIn predicate on the "len_field" field.
func LenFieldNotIn(vs ...string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldNotIn(FieldLenField, vs...))
}

// LenFieldGT applies the GT predicate on the "len_field" field.
func LenFieldGT(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGT(FieldLenField, v))
}

// LenFieldGTE applies the GTE predicate on the "len_field" field.
func LenFieldGTE(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldGTE(FieldLenField, v))
}

// LenFieldLT applies the LT predicate on the "len_field" field.
func LenFieldLT(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLT(FieldLenField, v))
}

// LenFieldLTE applies the LTE predicate on the "len_field" field.
func LenFieldLTE(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldLTE(FieldLenField, v))
}

// LenFieldContains applies the Contains predicate on the "len_field" field.
func LenFieldContains(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldContains(FieldLenField, v))
}

// LenFieldHasPrefix applies the HasPrefix predicate on the "len_field" field.
func LenFieldHasPrefix(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldHasPrefix(FieldLenField, v))
}

// LenFieldHasSuffix applies the HasSuffix predicate on the "len_field" field.
func LenFieldHasSuffix(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldHasSuffix(FieldLenField, v))
}

// LenFieldEqualFold applies the EqualFold predicate on the "len_field" field.
func LenFieldEqualFold(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldEqualFold(FieldLenField, v))
}

// LenFieldContainsFold applies the ContainsFold predicate on the "len_field" field.
func LenFieldContainsFold(v string) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.FieldContainsFold(FieldLenField, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StringCodePointBounds) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StringCodePointBounds) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StringCodePointBounds) predicate.StringCodePointBounds {
	return predicate.StringCodePointBounds(sql.NotPredicates(p))
}
