// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/mixedfieldrules"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/residualcel"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MixedFieldRules is the client for interacting with the MixedFieldRules builders.
	MixedFieldRules *MixedFieldRulesClient
	// ResidualCel is the client for interacting with the ResidualCel builders.
	ResidualCel *ResidualCelClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MixedFieldRules = NewMixedFieldRulesClient(c.config)
	c.ResidualCel = NewResidualCelClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		MixedFieldRules: NewMixedFieldRulesClient(cfg),
		ResidualCel:     NewResidualCelClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		MixedFieldRules: NewMixedFieldRulesClient(cfg),
		ResidualCel:     NewResidualCelClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MixedFieldRules.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MixedFieldRules.Use(hooks...)
	c.ResidualCel.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.MixedFieldRules.Intercept(interceptors...)
	c.ResidualCel.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *MixedFieldRulesMutation:
		return c.MixedFieldRules.mutate(ctx, m)
	case *ResidualCelMutation:
		return c.ResidualCel.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// MixedFieldRulesClient is a client for the MixedFieldRules schema.
type MixedFieldRulesClient struct {
	config
}

// NewMixedFieldRulesClient returns a client for the MixedFieldRules from the given config.
func NewMixedFieldRulesClient(c config) *MixedFieldRulesClient {
	return &MixedFieldRulesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mixedfieldrules.Hooks(f(g(h())))`.
func (c *MixedFieldRulesClient) Use(hooks ...Hook) {
	c.hooks.MixedFieldRules = append(c.hooks.MixedFieldRules, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mixedfieldrules.Intercept(f(g(h())))`.
func (c *MixedFieldRulesClient) Intercept(interceptors ...Interceptor) {
	c.inters.MixedFieldRules = append(c.inters.MixedFieldRules, interceptors...)
}

// Create returns a builder for creating a MixedFieldRules entity.
func (c *MixedFieldRulesClient) Create() *MixedFieldRulesCreate {
	mutation := newMixedFieldRulesMutation(c.config, OpCreate)
	return &MixedFieldRulesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MixedFieldRules entities.
func (c *MixedFieldRulesClient) CreateBulk(builders ...*MixedFieldRulesCreate) *MixedFieldRulesCreateBulk {
	return &MixedFieldRulesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MixedFieldRulesClient) MapCreateBulk(slice any, setFunc func(*MixedFieldRulesCreate, int)) *MixedFieldRulesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MixedFieldRulesCreateBulk{err: fmt.Errorf("calling to MixedFieldRulesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MixedFieldRulesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MixedFieldRulesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MixedFieldRules.
func (c *MixedFieldRulesClient) Update() *MixedFieldRulesUpdate {
	mutation := newMixedFieldRulesMutation(c.config, OpUpdate)
	return &MixedFieldRulesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MixedFieldRulesClient) UpdateOne(_m *MixedFieldRules) *MixedFieldRulesUpdateOne {
	mutation := newMixedFieldRulesMutation(c.config, OpUpdateOne, withMixedFieldRules(_m))
	return &MixedFieldRulesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MixedFieldRulesClient) UpdateOneID(id int) *MixedFieldRulesUpdateOne {
	mutation := newMixedFieldRulesMutation(c.config, OpUpdateOne, withMixedFieldRulesID(id))
	return &MixedFieldRulesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MixedFieldRules.
func (c *MixedFieldRulesClient) Delete() *MixedFieldRulesDelete {
	mutation := newMixedFieldRulesMutation(c.config, OpDelete)
	return &MixedFieldRulesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MixedFieldRulesClient) DeleteOne(_m *MixedFieldRules) *MixedFieldRulesDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MixedFieldRulesClient) DeleteOneID(id int) *MixedFieldRulesDeleteOne {
	builder := c.Delete().Where(mixedfieldrules.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MixedFieldRulesDeleteOne{builder}
}

// Query returns a query builder for MixedFieldRules.
func (c *MixedFieldRulesClient) Query() *MixedFieldRulesQuery {
	return &MixedFieldRulesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMixedFieldRules},
		inters: c.Interceptors(),
	}
}

// Get returns a MixedFieldRules entity by its id.
func (c *MixedFieldRulesClient) Get(ctx context.Context, id int) (*MixedFieldRules, error) {
	return c.Query().Where(mixedfieldrules.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MixedFieldRulesClient) GetX(ctx context.Context, id int) *MixedFieldRules {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MixedFieldRulesClient) Hooks() []Hook {
	hooks := c.hooks.MixedFieldRules
	return append(hooks[:len(hooks):len(hooks)], mixedfieldrules.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *MixedFieldRulesClient) Interceptors() []Interceptor {
	return c.inters.MixedFieldRules
}

func (c *MixedFieldRulesClient) mutate(ctx context.Context, m *MixedFieldRulesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MixedFieldRulesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MixedFieldRulesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MixedFieldRulesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MixedFieldRulesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MixedFieldRules mutation op: %q", m.Op())
	}
}

// ResidualCelClient is a client for the ResidualCel schema.
type ResidualCelClient struct {
	config
}

// NewResidualCelClient returns a client for the ResidualCel from the given config.
func NewResidualCelClient(c config) *ResidualCelClient {
	return &ResidualCelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `residualcel.Hooks(f(g(h())))`.
func (c *ResidualCelClient) Use(hooks ...Hook) {
	c.hooks.ResidualCel = append(c.hooks.ResidualCel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `residualcel.Intercept(f(g(h())))`.
func (c *ResidualCelClient) Intercept(interceptors ...Interceptor) {
	c.inters.ResidualCel = append(c.inters.ResidualCel, interceptors...)
}

// Create returns a builder for creating a ResidualCel entity.
func (c *ResidualCelClient) Create() *ResidualCelCreate {
	mutation := newResidualCelMutation(c.config, OpCreate)
	return &ResidualCelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ResidualCel entities.
func (c *ResidualCelClient) CreateBulk(builders ...*ResidualCelCreate) *ResidualCelCreateBulk {
	return &ResidualCelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ResidualCelClient) MapCreateBulk(slice any, setFunc func(*ResidualCelCreate, int)) *ResidualCelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ResidualCelCreateBulk{err: fmt.Errorf("calling to ResidualCelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ResidualCelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ResidualCelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ResidualCel.
func (c *ResidualCelClient) Update() *ResidualCelUpdate {
	mutation := newResidualCelMutation(c.config, OpUpdate)
	return &ResidualCelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ResidualCelClient) UpdateOne(_m *ResidualCel) *ResidualCelUpdateOne {
	mutation := newResidualCelMutation(c.config, OpUpdateOne, withResidualCel(_m))
	return &ResidualCelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ResidualCelClient) UpdateOneID(id int) *ResidualCelUpdateOne {
	mutation := newResidualCelMutation(c.config, OpUpdateOne, withResidualCelID(id))
	return &ResidualCelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ResidualCel.
func (c *ResidualCelClient) Delete() *ResidualCelDelete {
	mutation := newResidualCelMutation(c.config, OpDelete)
	return &ResidualCelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ResidualCelClient) DeleteOne(_m *ResidualCel) *ResidualCelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ResidualCelClient) DeleteOneID(id int) *ResidualCelDeleteOne {
	builder := c.Delete().Where(residualcel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ResidualCelDeleteOne{builder}
}

// Query returns a query builder for ResidualCel.
func (c *ResidualCelClient) Query() *ResidualCelQuery {
	return &ResidualCelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeResidualCel},
		inters: c.Interceptors(),
	}
}

// Get returns a ResidualCel entity by its id.
func (c *ResidualCelClient) Get(ctx context.Context, id int) (*ResidualCel, error) {
	return c.Query().Where(residualcel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ResidualCelClient) GetX(ctx context.Context, id int) *ResidualCel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ResidualCelClient) Hooks() []Hook {
	hooks := c.hooks.ResidualCel
	return append(hooks[:len(hooks):len(hooks)], residualcel.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ResidualCelClient) Interceptors() []Interceptor {
	return c.inters.ResidualCel
}

func (c *ResidualCelClient) mutate(ctx context.Context, m *ResidualCelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ResidualCelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ResidualCelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ResidualCelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ResidualCelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ResidualCel mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		MixedFieldRules, ResidualCel []ent.Hook
	}
	inters struct {
		MixedFieldRules, ResidualCel []ent.Interceptor
	}
)
