// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/ignoreifzerowithcel"
)

// IgnoreIfZeroWithCelCreate is the builder for creating a IgnoreIfZeroWithCel entity.
type IgnoreIfZeroWithCelCreate struct {
	config
	mutation *IgnoreIfZeroWithCelMutation
	hooks    []Hook
}

// SetZeroable sets the "zeroable" field.
func (_c *IgnoreIfZeroWithCelCreate) SetZeroable(v string) *IgnoreIfZeroWithCelCreate {
	_c.mutation.SetZeroable(v)
	return _c
}

// SetNillableZeroable sets the "zeroable" field if the given value is not nil.
func (_c *IgnoreIfZeroWithCelCreate) SetNillableZeroable(v *string) *IgnoreIfZeroWithCelCreate {
	if v != nil {
		_c.SetZeroable(*v)
	}
	return _c
}

// SetZeroableNum sets the "zeroable_num" field.
func (_c *IgnoreIfZeroWithCelCreate) SetZeroableNum(v int32) *IgnoreIfZeroWithCelCreate {
	_c.mutation.SetZeroableNum(v)
	return _c
}

// SetNillableZeroableNum sets the "zeroable_num" field if the given value is not nil.
func (_c *IgnoreIfZeroWithCelCreate) SetNillableZeroableNum(v *int32) *IgnoreIfZeroWithCelCreate {
	if v != nil {
		_c.SetZeroableNum(*v)
	}
	return _c
}

// Mutation returns the IgnoreIfZeroWithCelMutation object of the builder.
func (_c *IgnoreIfZeroWithCelCreate) Mutation() *IgnoreIfZeroWithCelMutation {
	return _c.mutation
}

// Save creates the IgnoreIfZeroWithCel in the database.
func (_c *IgnoreIfZeroWithCelCreate) Save(ctx context.Context) (*IgnoreIfZeroWithCel, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IgnoreIfZeroWithCelCreate) SaveX(ctx context.Context) *IgnoreIfZeroWithCel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IgnoreIfZeroWithCelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IgnoreIfZeroWithCelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IgnoreIfZeroWithCelCreate) defaults() error {
	if _, ok := _c.mutation.Zeroable(); !ok {
		v := ignoreifzerowithcel.DefaultZeroable
		_c.mutation.SetZeroable(v)
	}
	if _, ok := _c.mutation.ZeroableNum(); !ok {
		v := ignoreifzerowithcel.DefaultZeroableNum
		_c.mutation.SetZeroableNum(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *IgnoreIfZeroWithCelCreate) check() error {
	if _, ok := _c.mutation.Zeroable(); !ok {
		return &ValidationError{Name: "zeroable", err: errors.New(`ent: missing required field "IgnoreIfZeroWithCel.zeroable"`)}
	}
	if _, ok := _c.mutation.ZeroableNum(); !ok {
		return &ValidationError{Name: "zeroable_num", err: errors.New(`ent: missing required field "IgnoreIfZeroWithCel.zeroable_num"`)}
	}
	return nil
}

func (_c *IgnoreIfZeroWithCelCreate) sqlSave(ctx context.Context) (*IgnoreIfZeroWithCel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IgnoreIfZeroWithCelCreate) createSpec() (*IgnoreIfZeroWithCel, *sqlgraph.CreateSpec) {
	var (
		_node = &IgnoreIfZeroWithCel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ignoreifzerowithcel.Table, sqlgraph.NewFieldSpec(ignoreifzerowithcel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Zeroable(); ok {
		_spec.SetField(ignoreifzerowithcel.FieldZeroable, field.TypeString, value)
		_node.Zeroable = value
	}
	if value, ok := _c.mutation.ZeroableNum(); ok {
		_spec.SetField(ignoreifzerowithcel.FieldZeroableNum, field.TypeInt32, value)
		_node.ZeroableNum = value
	}
	return _node, _spec
}

// IgnoreIfZeroWithCelCreateBulk is the builder for creating many IgnoreIfZeroWithCel entities in bulk.
type IgnoreIfZeroWithCelCreateBulk struct {
	config
	err      error
	builders []*IgnoreIfZeroWithCelCreate
}

// Save creates the IgnoreIfZeroWithCel entities in the database.
func (_c *IgnoreIfZeroWithCelCreateBulk) Save(ctx context.Context) ([]*IgnoreIfZeroWithCel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IgnoreIfZeroWithCel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IgnoreIfZeroWithCelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IgnoreIfZeroWithCelCreateBulk) SaveX(ctx context.Context) []*IgnoreIfZeroWithCel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IgnoreIfZeroWithCelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IgnoreIfZeroWithCelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
