// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/int32adjacent"
)

// Int32Adjacent is the model entity for the Int32Adjacent schema.
type Int32Adjacent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CoincidentField holds the value of the "coincident_field" field.
	CoincidentField int32 `json:"coincident_field,omitempty"`
	// CrossedField holds the value of the "crossed_field" field.
	CrossedField int32 `json:"crossed_field,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Int32Adjacent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case int32adjacent.FieldID, int32adjacent.FieldCoincidentField, int32adjacent.FieldCrossedField:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Int32Adjacent fields.
func (_m *Int32Adjacent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case int32adjacent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case int32adjacent.FieldCoincidentField:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field coincident_field", values[i])
			} else if value.Valid {
				_m.CoincidentField = int32(value.Int64)
			}
		case int32adjacent.FieldCrossedField:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field crossed_field", values[i])
			} else if value.Valid {
				_m.CrossedField = int32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Int32Adjacent.
// This includes values selected through modifiers, order, etc.
func (_m *Int32Adjacent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Int32Adjacent.
// Note that you need to call Int32Adjacent.Unwrap() before calling this method if this Int32Adjacent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Int32Adjacent) Update() *Int32AdjacentUpdateOne {
	return NewInt32AdjacentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Int32Adjacent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Int32Adjacent) Unwrap() *Int32Adjacent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Int32Adjacent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Int32Adjacent) String() string {
	var builder strings.Builder
	builder.WriteString("Int32Adjacent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("coincident_field=")
	builder.WriteString(fmt.Sprintf("%v", _m.CoincidentField))
	builder.WriteString(", ")
	builder.WriteString("crossed_field=")
	builder.WriteString(fmt.Sprintf("%v", _m.CrossedField))
	builder.WriteByte(')')
	return builder.String()
}

// Int32Adjacents is a parsable slice of Int32Adjacent.
type Int32Adjacents []*Int32Adjacent
