// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/int32comparators"
)

// Int32ComparatorsCreate is the builder for creating a Int32Comparators entity.
type Int32ComparatorsCreate struct {
	config
	mutation *Int32ComparatorsMutation
	hooks    []Hook
}

// SetGtField sets the "gt_field" field.
func (_c *Int32ComparatorsCreate) SetGtField(v int32) *Int32ComparatorsCreate {
	_c.mutation.SetGtField(v)
	return _c
}

// SetNillableGtField sets the "gt_field" field if the given value is not nil.
func (_c *Int32ComparatorsCreate) SetNillableGtField(v *int32) *Int32ComparatorsCreate {
	if v != nil {
		_c.SetGtField(*v)
	}
	return _c
}

// SetGteField sets the "gte_field" field.
func (_c *Int32ComparatorsCreate) SetGteField(v int32) *Int32ComparatorsCreate {
	_c.mutation.SetGteField(v)
	return _c
}

// SetNillableGteField sets the "gte_field" field if the given value is not nil.
func (_c *Int32ComparatorsCreate) SetNillableGteField(v *int32) *Int32ComparatorsCreate {
	if v != nil {
		_c.SetGteField(*v)
	}
	return _c
}

// SetLtField sets the "lt_field" field.
func (_c *Int32ComparatorsCreate) SetLtField(v int32) *Int32ComparatorsCreate {
	_c.mutation.SetLtField(v)
	return _c
}

// SetNillableLtField sets the "lt_field" field if the given value is not nil.
func (_c *Int32ComparatorsCreate) SetNillableLtField(v *int32) *Int32ComparatorsCreate {
	if v != nil {
		_c.SetLtField(*v)
	}
	return _c
}

// SetLteField sets the "lte_field" field.
func (_c *Int32ComparatorsCreate) SetLteField(v int32) *Int32ComparatorsCreate {
	_c.mutation.SetLteField(v)
	return _c
}

// SetNillableLteField sets the "lte_field" field if the given value is not nil.
func (_c *Int32ComparatorsCreate) SetNillableLteField(v *int32) *Int32ComparatorsCreate {
	if v != nil {
		_c.SetLteField(*v)
	}
	return _c
}

// SetPositiveField sets the "positive_field" field.
func (_c *Int32ComparatorsCreate) SetPositiveField(v int32) *Int32ComparatorsCreate {
	_c.mutation.SetPositiveField(v)
	return _c
}

// SetNillablePositiveField sets the "positive_field" field if the given value is not nil.
func (_c *Int32ComparatorsCreate) SetNillablePositiveField(v *int32) *Int32ComparatorsCreate {
	if v != nil {
		_c.SetPositiveField(*v)
	}
	return _c
}

// SetRangeField sets the "range_field" field.
func (_c *Int32ComparatorsCreate) SetRangeField(v int32) *Int32ComparatorsCreate {
	_c.mutation.SetRangeField(v)
	return _c
}

// SetNillableRangeField sets the "range_field" field if the given value is not nil.
func (_c *Int32ComparatorsCreate) SetNillableRangeField(v *int32) *Int32ComparatorsCreate {
	if v != nil {
		_c.SetRangeField(*v)
	}
	return _c
}

// SetNoRulesField sets the "no_rules_field" field.
func (_c *Int32ComparatorsCreate) SetNoRulesField(v int32) *Int32ComparatorsCreate {
	_c.mutation.SetNoRulesField(v)
	return _c
}

// SetNillableNoRulesField sets the "no_rules_field" field if the given value is not nil.
func (_c *Int32ComparatorsCreate) SetNillableNoRulesField(v *int32) *Int32ComparatorsCreate {
	if v != nil {
		_c.SetNoRulesField(*v)
	}
	return _c
}

// Mutation returns the Int32ComparatorsMutation object of the builder.
func (_c *Int32ComparatorsCreate) Mutation() *Int32ComparatorsMutation {
	return _c.mutation
}

// Save creates the Int32Comparators in the database.
func (_c *Int32ComparatorsCreate) Save(ctx context.Context) (*Int32Comparators, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *Int32ComparatorsCreate) SaveX(ctx context.Context) *Int32Comparators {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Int32ComparatorsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Int32ComparatorsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *Int32ComparatorsCreate) defaults() error {
	if _, ok := _c.mutation.GtField(); !ok {
		v := int32comparators.DefaultGtField
		_c.mutation.SetGtField(v)
	}
	if _, ok := _c.mutation.GteField(); !ok {
		v := int32comparators.DefaultGteField
		_c.mutation.SetGteField(v)
	}
	if _, ok := _c.mutation.LtField(); !ok {
		v := int32comparators.DefaultLtField
		_c.mutation.SetLtField(v)
	}
	if _, ok := _c.mutation.LteField(); !ok {
		v := int32comparators.DefaultLteField
		_c.mutation.SetLteField(v)
	}
	if _, ok := _c.mutation.PositiveField(); !ok {
		v := int32comparators.DefaultPositiveField
		_c.mutation.SetPositiveField(v)
	}
	if _, ok := _c.mutation.RangeField(); !ok {
		v := int32comparators.DefaultRangeField
		_c.mutation.SetRangeField(v)
	}
	if _, ok := _c.mutation.NoRulesField(); !ok {
		v := int32comparators.DefaultNoRulesField
		_c.mutation.SetNoRulesField(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *Int32ComparatorsCreate) check() error {
	if _, ok := _c.mutation.GtField(); !ok {
		return &ValidationError{Name: "gt_field", err: errors.New(`ent: missing required field "Int32Comparators.gt_field"`)}
	}
	if v, ok := _c.mutation.GtField(); ok {
		if err := int32comparators.GtFieldValidator(v); err != nil {
			return &ValidationError{Name: "gt_field", err: fmt.Errorf(`ent: validator failed for field "Int32Comparators.gt_field": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GteField(); !ok {
		return &ValidationError{Name: "gte_field", err: errors.New(`ent: missing required field "Int32Comparators.gte_field"`)}
	}
	if v, ok := _c.mutation.GteField(); ok {
		if err := int32comparators.GteFieldValidator(v); err != nil {
			return &ValidationError{Name: "gte_field", err: fmt.Errorf(`ent: validator failed for field "Int32Comparators.gte_field": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LtField(); !ok {
		return &ValidationError{Name: "lt_field", err: errors.New(`ent: missing required field "Int32Comparators.lt_field"`)}
	}
	if v, ok := _c.mutation.LtField(); ok {
		if err := int32comparators.LtFieldValidator(v); err != nil {
			return &ValidationError{Name: "lt_field", err: fmt.Errorf(`ent: validator failed for field "Int32Comparators.lt_field": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LteField(); !ok {
		return &ValidationError{Name: "lte_field", err: errors.New(`ent: missing required field "Int32Comparators.lte_field"`)}
	}
	if v, ok := _c.mutation.LteField(); ok {
		if err := int32comparators.LteFieldValidator(v); err != nil {
			return &ValidationError{Name: "lte_field", err: fmt.Errorf(`ent: validator failed for field "Int32Comparators.lte_field": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PositiveField(); !ok {
		return &ValidationError{Name: "positive_field", err: errors.New(`ent: missing required field "Int32Comparators.positive_field"`)}
	}
	if v, ok := _c.mutation.PositiveField(); ok {
		if err := int32comparators.PositiveFieldValidator(v); err != nil {
			return &ValidationError{Name: "positive_field", err: fmt.Errorf(`ent: validator failed for field "Int32Comparators.positive_field": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RangeField(); !ok {
		return &ValidationError{Name: "range_field", err: errors.New(`ent: missing required field "Int32Comparators.range_field"`)}
	}
	if v, ok := _c.mutation.RangeField(); ok {
		if err := int32comparators.RangeFieldValidator(v); err != nil {
			return &ValidationError{Name: "range_field", err: fmt.Errorf(`ent: validator failed for field "Int32Comparators.range_field": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NoRulesField(); !ok {
		return &ValidationError{Name: "no_rules_field", err: errors.New(`ent: missing required field "Int32Comparators.no_rules_field"`)}
	}
	return nil
}

func (_c *Int32ComparatorsCreate) sqlSave(ctx context.Context) (*Int32Comparators, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *Int32ComparatorsCreate) createSpec() (*Int32Comparators, *sqlgraph.CreateSpec) {
	var (
		_node = &Int32Comparators{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(int32comparators.Table, sqlgraph.NewFieldSpec(int32comparators.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GtField(); ok {
		_spec.SetField(int32comparators.FieldGtField, field.TypeInt32, value)
		_node.GtField = value
	}
	if value, ok := _c.mutation.GteField(); ok {
		_spec.SetField(int32comparators.FieldGteField, field.TypeInt32, value)
		_node.GteField = value
	}
	if value, ok := _c.mutation.LtField(); ok {
		_spec.SetField(int32comparators.FieldLtField, field.TypeInt32, value)
		_node.LtField = value
	}
	if value, ok := _c.mutation.LteField(); ok {
		_spec.SetField(int32comparators.FieldLteField, field.TypeInt32, value)
		_node.LteField = value
	}
	if value, ok := _c.mutation.PositiveField(); ok {
		_spec.SetField(int32comparators.FieldPositiveField, field.TypeInt32, value)
		_node.PositiveField = value
	}
	if value, ok := _c.mutation.RangeField(); ok {
		_spec.SetField(int32comparators.FieldRangeField, field.TypeInt32, value)
		_node.RangeField = value
	}
	if value, ok := _c.mutation.NoRulesField(); ok {
		_spec.SetField(int32comparators.FieldNoRulesField, field.TypeInt32, value)
		_node.NoRulesField = value
	}
	return _node, _spec
}

// Int32ComparatorsCreateBulk is the builder for creating many Int32Comparators entities in bulk.
type Int32ComparatorsCreateBulk struct {
	config
	err      error
	builders []*Int32ComparatorsCreate
}

// Save creates the Int32Comparators entities in the database.
func (_c *Int32ComparatorsCreateBulk) Save(ctx context.Context) ([]*Int32Comparators, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Int32Comparators, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Int32ComparatorsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *Int32ComparatorsCreateBulk) SaveX(ctx context.Context) []*Int32Comparators {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Int32ComparatorsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Int32ComparatorsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
