// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/messageruleoneof"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// MessageRuleOneofUpdate is the builder for updating MessageRuleOneof entities.
type MessageRuleOneofUpdate struct {
	config
	hooks    []Hook
	mutation *MessageRuleOneofMutation
}

// Where appends a list predicates to the MessageRuleOneofUpdate builder.
func (_u *MessageRuleOneofUpdate) Where(ps ...predicate.MessageRuleOneof) *MessageRuleOneofUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLo sets the "lo" field.
func (_u *MessageRuleOneofUpdate) SetLo(v int32) *MessageRuleOneofUpdate {
	_u.mutation.ResetLo()
	_u.mutation.SetLo(v)
	return _u
}

// SetNillableLo sets the "lo" field if the given value is not nil.
func (_u *MessageRuleOneofUpdate) SetNillableLo(v *int32) *MessageRuleOneofUpdate {
	if v != nil {
		_u.SetLo(*v)
	}
	return _u
}

// AddLo adds value to the "lo" field.
func (_u *MessageRuleOneofUpdate) AddLo(v int32) *MessageRuleOneofUpdate {
	_u.mutation.AddLo(v)
	return _u
}

// SetHi sets the "hi" field.
func (_u *MessageRuleOneofUpdate) SetHi(v int32) *MessageRuleOneofUpdate {
	_u.mutation.ResetHi()
	_u.mutation.SetHi(v)
	return _u
}

// SetNillableHi sets the "hi" field if the given value is not nil.
func (_u *MessageRuleOneofUpdate) SetNillableHi(v *int32) *MessageRuleOneofUpdate {
	if v != nil {
		_u.SetHi(*v)
	}
	return _u
}

// AddHi adds value to the "hi" field.
func (_u *MessageRuleOneofUpdate) AddHi(v int32) *MessageRuleOneofUpdate {
	_u.mutation.AddHi(v)
	return _u
}

// Mutation returns the MessageRuleOneofMutation object of the builder.
func (_u *MessageRuleOneofUpdate) Mutation() *MessageRuleOneofMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageRuleOneofUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageRuleOneofUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageRuleOneofUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageRuleOneofUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageRuleOneofUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(messageruleoneof.Table, messageruleoneof.Columns, sqlgraph.NewFieldSpec(messageruleoneof.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lo(); ok {
		_spec.SetField(messageruleoneof.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLo(); ok {
		_spec.AddField(messageruleoneof.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Hi(); ok {
		_spec.SetField(messageruleoneof.FieldHi, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedHi(); ok {
		_spec.AddField(messageruleoneof.FieldHi, field.TypeInt32, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messageruleoneof.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageRuleOneofUpdateOne is the builder for updating a single MessageRuleOneof entity.
type MessageRuleOneofUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageRuleOneofMutation
}

// SetLo sets the "lo" field.
func (_u *MessageRuleOneofUpdateOne) SetLo(v int32) *MessageRuleOneofUpdateOne {
	_u.mutation.ResetLo()
	_u.mutation.SetLo(v)
	return _u
}

// SetNillableLo sets the "lo" field if the given value is not nil.
func (_u *MessageRuleOneofUpdateOne) SetNillableLo(v *int32) *MessageRuleOneofUpdateOne {
	if v != nil {
		_u.SetLo(*v)
	}
	return _u
}

// AddLo adds value to the "lo" field.
func (_u *MessageRuleOneofUpdateOne) AddLo(v int32) *MessageRuleOneofUpdateOne {
	_u.mutation.AddLo(v)
	return _u
}

// SetHi sets the "hi" field.
func (_u *MessageRuleOneofUpdateOne) SetHi(v int32) *MessageRuleOneofUpdateOne {
	_u.mutation.ResetHi()
	_u.mutation.SetHi(v)
	return _u
}

// SetNillableHi sets the "hi" field if the given value is not nil.
func (_u *MessageRuleOneofUpdateOne) SetNillableHi(v *int32) *MessageRuleOneofUpdateOne {
	if v != nil {
		_u.SetHi(*v)
	}
	return _u
}

// AddHi adds value to the "hi" field.
func (_u *MessageRuleOneofUpdateOne) AddHi(v int32) *MessageRuleOneofUpdateOne {
	_u.mutation.AddHi(v)
	return _u
}

// Mutation returns the MessageRuleOneofMutation object of the builder.
func (_u *MessageRuleOneofUpdateOne) Mutation() *MessageRuleOneofMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageRuleOneofUpdate builder.
func (_u *MessageRuleOneofUpdateOne) Where(ps ...predicate.MessageRuleOneof) *MessageRuleOneofUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageRuleOneofUpdateOne) Select(field string, fields ...string) *MessageRuleOneofUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MessageRuleOneof entity.
func (_u *MessageRuleOneofUpdateOne) Save(ctx context.Context) (*MessageRuleOneof, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageRuleOneofUpdateOne) SaveX(ctx context.Context) *MessageRuleOneof {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageRuleOneofUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageRuleOneofUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageRuleOneofUpdateOne) sqlSave(ctx context.Context) (_node *MessageRuleOneof, err error) {
	_spec := sqlgraph.NewUpdateSpec(messageruleoneof.Table, messageruleoneof.Columns, sqlgraph.NewFieldSpec(messageruleoneof.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageRuleOneof.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messageruleoneof.FieldID)
		for _, f := range fields {
			if !messageruleoneof.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messageruleoneof.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lo(); ok {
		_spec.SetField(messageruleoneof.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLo(); ok {
		_spec.AddField(messageruleoneof.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Hi(); ok {
		_spec.SetField(messageruleoneof.FieldHi, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedHi(); ok {
		_spec.AddField(messageruleoneof.FieldHi, field.TypeInt32, value)
	}
	_node = &MessageRuleOneof{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messageruleoneof.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
