// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/messagerules"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// MessageRulesUpdate is the builder for updating MessageRules entities.
type MessageRulesUpdate struct {
	config
	hooks    []Hook
	mutation *MessageRulesMutation
}

// Where appends a list predicates to the MessageRulesUpdate builder.
func (_u *MessageRulesUpdate) Where(ps ...predicate.MessageRules) *MessageRulesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLo sets the "lo" field.
func (_u *MessageRulesUpdate) SetLo(v int32) *MessageRulesUpdate {
	_u.mutation.ResetLo()
	_u.mutation.SetLo(v)
	return _u
}

// SetNillableLo sets the "lo" field if the given value is not nil.
func (_u *MessageRulesUpdate) SetNillableLo(v *int32) *MessageRulesUpdate {
	if v != nil {
		_u.SetLo(*v)
	}
	return _u
}

// AddLo adds value to the "lo" field.
func (_u *MessageRulesUpdate) AddLo(v int32) *MessageRulesUpdate {
	_u.mutation.AddLo(v)
	return _u
}

// SetHi sets the "hi" field.
func (_u *MessageRulesUpdate) SetHi(v int32) *MessageRulesUpdate {
	_u.mutation.ResetHi()
	_u.mutation.SetHi(v)
	return _u
}

// SetNillableHi sets the "hi" field if the given value is not nil.
func (_u *MessageRulesUpdate) SetNillableHi(v *int32) *MessageRulesUpdate {
	if v != nil {
		_u.SetHi(*v)
	}
	return _u
}

// AddHi adds value to the "hi" field.
func (_u *MessageRulesUpdate) AddHi(v int32) *MessageRulesUpdate {
	_u.mutation.AddHi(v)
	return _u
}

// Mutation returns the MessageRulesMutation object of the builder.
func (_u *MessageRulesUpdate) Mutation() *MessageRulesMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageRulesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageRulesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageRulesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageRulesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageRulesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(messagerules.Table, messagerules.Columns, sqlgraph.NewFieldSpec(messagerules.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lo(); ok {
		_spec.SetField(messagerules.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLo(); ok {
		_spec.AddField(messagerules.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Hi(); ok {
		_spec.SetField(messagerules.FieldHi, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedHi(); ok {
		_spec.AddField(messagerules.FieldHi, field.TypeInt32, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagerules.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageRulesUpdateOne is the builder for updating a single MessageRules entity.
type MessageRulesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageRulesMutation
}

// SetLo sets the "lo" field.
func (_u *MessageRulesUpdateOne) SetLo(v int32) *MessageRulesUpdateOne {
	_u.mutation.ResetLo()
	_u.mutation.SetLo(v)
	return _u
}

// SetNillableLo sets the "lo" field if the given value is not nil.
func (_u *MessageRulesUpdateOne) SetNillableLo(v *int32) *MessageRulesUpdateOne {
	if v != nil {
		_u.SetLo(*v)
	}
	return _u
}

// AddLo adds value to the "lo" field.
func (_u *MessageRulesUpdateOne) AddLo(v int32) *MessageRulesUpdateOne {
	_u.mutation.AddLo(v)
	return _u
}

// SetHi sets the "hi" field.
func (_u *MessageRulesUpdateOne) SetHi(v int32) *MessageRulesUpdateOne {
	_u.mutation.ResetHi()
	_u.mutation.SetHi(v)
	return _u
}

// SetNillableHi sets the "hi" field if the given value is not nil.
func (_u *MessageRulesUpdateOne) SetNillableHi(v *int32) *MessageRulesUpdateOne {
	if v != nil {
		_u.SetHi(*v)
	}
	return _u
}

// AddHi adds value to the "hi" field.
func (_u *MessageRulesUpdateOne) AddHi(v int32) *MessageRulesUpdateOne {
	_u.mutation.AddHi(v)
	return _u
}

// Mutation returns the MessageRulesMutation object of the builder.
func (_u *MessageRulesUpdateOne) Mutation() *MessageRulesMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageRulesUpdate builder.
func (_u *MessageRulesUpdateOne) Where(ps ...predicate.MessageRules) *MessageRulesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageRulesUpdateOne) Select(field string, fields ...string) *MessageRulesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MessageRules entity.
func (_u *MessageRulesUpdateOne) Save(ctx context.Context) (*MessageRules, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageRulesUpdateOne) SaveX(ctx context.Context) *MessageRules {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageRulesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageRulesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageRulesUpdateOne) sqlSave(ctx context.Context) (_node *MessageRules, err error) {
	_spec := sqlgraph.NewUpdateSpec(messagerules.Table, messagerules.Columns, sqlgraph.NewFieldSpec(messagerules.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageRules.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagerules.FieldID)
		for _, f := range fields {
			if !messagerules.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messagerules.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lo(); ok {
		_spec.SetField(messagerules.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLo(); ok {
		_spec.AddField(messagerules.FieldLo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Hi(); ok {
		_spec.SetField(messagerules.FieldHi, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedHi(); ok {
		_spec.AddField(messagerules.FieldHi, field.TypeInt32, value)
	}
	_node = &MessageRules{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagerules.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
