// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/messagerulecelexpression"
)

// MessageRuleCelExpression is the model entity for the MessageRuleCelExpression schema.
type MessageRuleCelExpression struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Lo holds the value of the "lo" field.
	Lo int32 `json:"lo,omitempty"`
	// Hi holds the value of the "hi" field.
	Hi           int32 `json:"hi,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MessageRuleCelExpression) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case messagerulecelexpression.FieldID, messagerulecelexpression.FieldLo, messagerulecelexpression.FieldHi:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MessageRuleCelExpression fields.
func (_m *MessageRuleCelExpression) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case messagerulecelexpression.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case messagerulecelexpression.FieldLo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lo", values[i])
			} else if value.Valid {
				_m.Lo = int32(value.Int64)
			}
		case messagerulecelexpression.FieldHi:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hi", values[i])
			} else if value.Valid {
				_m.Hi = int32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MessageRuleCelExpression.
// This includes values selected through modifiers, order, etc.
func (_m *MessageRuleCelExpression) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MessageRuleCelExpression.
// Note that you need to call MessageRuleCelExpression.Unwrap() before calling this method if this MessageRuleCelExpression
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MessageRuleCelExpression) Update() *MessageRuleCelExpressionUpdateOne {
	return NewMessageRuleCelExpressionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MessageRuleCelExpression entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MessageRuleCelExpression) Unwrap() *MessageRuleCelExpression {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MessageRuleCelExpression is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MessageRuleCelExpression) String() string {
	var builder strings.Builder
	builder.WriteString("MessageRuleCelExpression(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("lo=")
	builder.WriteString(fmt.Sprintf("%v", _m.Lo))
	builder.WriteString(", ")
	builder.WriteString("hi=")
	builder.WriteString(fmt.Sprintf("%v", _m.Hi))
	builder.WriteByte(')')
	return builder.String()
}

// MessageRuleCelExpressions is a parsable slice of MessageRuleCelExpression.
type MessageRuleCelExpressions []*MessageRuleCelExpression
