// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/messagerulecelexpression"
)

// MessageRuleCelExpressionCreate is the builder for creating a MessageRuleCelExpression entity.
type MessageRuleCelExpressionCreate struct {
	config
	mutation *MessageRuleCelExpressionMutation
	hooks    []Hook
}

// SetLo sets the "lo" field.
func (_c *MessageRuleCelExpressionCreate) SetLo(v int32) *MessageRuleCelExpressionCreate {
	_c.mutation.SetLo(v)
	return _c
}

// SetNillableLo sets the "lo" field if the given value is not nil.
func (_c *MessageRuleCelExpressionCreate) SetNillableLo(v *int32) *MessageRuleCelExpressionCreate {
	if v != nil {
		_c.SetLo(*v)
	}
	return _c
}

// SetHi sets the "hi" field.
func (_c *MessageRuleCelExpressionCreate) SetHi(v int32) *MessageRuleCelExpressionCreate {
	_c.mutation.SetHi(v)
	return _c
}

// SetNillableHi sets the "hi" field if the given value is not nil.
func (_c *MessageRuleCelExpressionCreate) SetNillableHi(v *int32) *MessageRuleCelExpressionCreate {
	if v != nil {
		_c.SetHi(*v)
	}
	return _c
}

// Mutation returns the MessageRuleCelExpressionMutation object of the builder.
func (_c *MessageRuleCelExpressionCreate) Mutation() *MessageRuleCelExpressionMutation {
	return _c.mutation
}

// Save creates the MessageRuleCelExpression in the database.
func (_c *MessageRuleCelExpressionCreate) Save(ctx context.Context) (*MessageRuleCelExpression, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageRuleCelExpressionCreate) SaveX(ctx context.Context) *MessageRuleCelExpression {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageRuleCelExpressionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageRuleCelExpressionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageRuleCelExpressionCreate) defaults() error {
	if _, ok := _c.mutation.Lo(); !ok {
		v := messagerulecelexpression.DefaultLo
		_c.mutation.SetLo(v)
	}
	if _, ok := _c.mutation.Hi(); !ok {
		v := messagerulecelexpression.DefaultHi
		_c.mutation.SetHi(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageRuleCelExpressionCreate) check() error {
	if _, ok := _c.mutation.Lo(); !ok {
		return &ValidationError{Name: "lo", err: errors.New(`ent: missing required field "MessageRuleCelExpression.lo"`)}
	}
	if _, ok := _c.mutation.Hi(); !ok {
		return &ValidationError{Name: "hi", err: errors.New(`ent: missing required field "MessageRuleCelExpression.hi"`)}
	}
	return nil
}

func (_c *MessageRuleCelExpressionCreate) sqlSave(ctx context.Context) (*MessageRuleCelExpression, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageRuleCelExpressionCreate) createSpec() (*MessageRuleCelExpression, *sqlgraph.CreateSpec) {
	var (
		_node = &MessageRuleCelExpression{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(messagerulecelexpression.Table, sqlgraph.NewFieldSpec(messagerulecelexpression.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Lo(); ok {
		_spec.SetField(messagerulecelexpression.FieldLo, field.TypeInt32, value)
		_node.Lo = value
	}
	if value, ok := _c.mutation.Hi(); ok {
		_spec.SetField(messagerulecelexpression.FieldHi, field.TypeInt32, value)
		_node.Hi = value
	}
	return _node, _spec
}

// MessageRuleCelExpressionCreateBulk is the builder for creating many MessageRuleCelExpression entities in bulk.
type MessageRuleCelExpressionCreateBulk struct {
	config
	err      error
	builders []*MessageRuleCelExpressionCreate
}

// Save creates the MessageRuleCelExpression entities in the database.
func (_c *MessageRuleCelExpressionCreateBulk) Save(ctx context.Context) ([]*MessageRuleCelExpression, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MessageRuleCelExpression, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageRuleCelExpressionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageRuleCelExpressionCreateBulk) SaveX(ctx context.Context) []*MessageRuleCelExpression {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageRuleCelExpressionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageRuleCelExpressionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
