// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/mixedfieldrules"
)

// MixedFieldRulesCreate is the builder for creating a MixedFieldRules entity.
type MixedFieldRulesCreate struct {
	config
	mutation *MixedFieldRulesMutation
	hooks    []Hook
}

// SetBoth sets the "both" field.
func (_c *MixedFieldRulesCreate) SetBoth(v string) *MixedFieldRulesCreate {
	_c.mutation.SetBoth(v)
	return _c
}

// SetNillableBoth sets the "both" field if the given value is not nil.
func (_c *MixedFieldRulesCreate) SetNillableBoth(v *string) *MixedFieldRulesCreate {
	if v != nil {
		_c.SetBoth(*v)
	}
	return _c
}

// SetStandardOnly sets the "standard_only" field.
func (_c *MixedFieldRulesCreate) SetStandardOnly(v string) *MixedFieldRulesCreate {
	_c.mutation.SetStandardOnly(v)
	return _c
}

// SetNillableStandardOnly sets the "standard_only" field if the given value is not nil.
func (_c *MixedFieldRulesCreate) SetNillableStandardOnly(v *string) *MixedFieldRulesCreate {
	if v != nil {
		_c.SetStandardOnly(*v)
	}
	return _c
}

// SetCelOnly sets the "cel_only" field.
func (_c *MixedFieldRulesCreate) SetCelOnly(v string) *MixedFieldRulesCreate {
	_c.mutation.SetCelOnly(v)
	return _c
}

// SetNillableCelOnly sets the "cel_only" field if the given value is not nil.
func (_c *MixedFieldRulesCreate) SetNillableCelOnly(v *string) *MixedFieldRulesCreate {
	if v != nil {
		_c.SetCelOnly(*v)
	}
	return _c
}

// Mutation returns the MixedFieldRulesMutation object of the builder.
func (_c *MixedFieldRulesCreate) Mutation() *MixedFieldRulesMutation {
	return _c.mutation
}

// Save creates the MixedFieldRules in the database.
func (_c *MixedFieldRulesCreate) Save(ctx context.Context) (*MixedFieldRules, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MixedFieldRulesCreate) SaveX(ctx context.Context) *MixedFieldRules {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MixedFieldRulesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MixedFieldRulesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MixedFieldRulesCreate) defaults() error {
	if _, ok := _c.mutation.Both(); !ok {
		v := mixedfieldrules.DefaultBoth
		_c.mutation.SetBoth(v)
	}
	if _, ok := _c.mutation.StandardOnly(); !ok {
		v := mixedfieldrules.DefaultStandardOnly
		_c.mutation.SetStandardOnly(v)
	}
	if _, ok := _c.mutation.CelOnly(); !ok {
		v := mixedfieldrules.DefaultCelOnly
		_c.mutation.SetCelOnly(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *MixedFieldRulesCreate) check() error {
	if _, ok := _c.mutation.Both(); !ok {
		return &ValidationError{Name: "both", err: errors.New(`ent: missing required field "MixedFieldRules.both"`)}
	}
	if v, ok := _c.mutation.Both(); ok {
		if err := mixedfieldrules.BothValidator(v); err != nil {
			return &ValidationError{Name: "both", err: fmt.Errorf(`ent: validator failed for field "MixedFieldRules.both": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StandardOnly(); !ok {
		return &ValidationError{Name: "standard_only", err: errors.New(`ent: missing required field "MixedFieldRules.standard_only"`)}
	}
	if v, ok := _c.mutation.StandardOnly(); ok {
		if err := mixedfieldrules.StandardOnlyValidator(v); err != nil {
			return &ValidationError{Name: "standard_only", err: fmt.Errorf(`ent: validator failed for field "MixedFieldRules.standard_only": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CelOnly(); !ok {
		return &ValidationError{Name: "cel_only", err: errors.New(`ent: missing required field "MixedFieldRules.cel_only"`)}
	}
	return nil
}

func (_c *MixedFieldRulesCreate) sqlSave(ctx context.Context) (*MixedFieldRules, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MixedFieldRulesCreate) createSpec() (*MixedFieldRules, *sqlgraph.CreateSpec) {
	var (
		_node = &MixedFieldRules{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mixedfieldrules.Table, sqlgraph.NewFieldSpec(mixedfieldrules.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Both(); ok {
		_spec.SetField(mixedfieldrules.FieldBoth, field.TypeString, value)
		_node.Both = value
	}
	if value, ok := _c.mutation.StandardOnly(); ok {
		_spec.SetField(mixedfieldrules.FieldStandardOnly, field.TypeString, value)
		_node.StandardOnly = value
	}
	if value, ok := _c.mutation.CelOnly(); ok {
		_spec.SetField(mixedfieldrules.FieldCelOnly, field.TypeString, value)
		_node.CelOnly = value
	}
	return _node, _spec
}

// MixedFieldRulesCreateBulk is the builder for creating many MixedFieldRules entities in bulk.
type MixedFieldRulesCreateBulk struct {
	config
	err      error
	builders []*MixedFieldRulesCreate
}

// Save creates the MixedFieldRules entities in the database.
func (_c *MixedFieldRulesCreateBulk) Save(ctx context.Context) ([]*MixedFieldRules, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MixedFieldRules, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MixedFieldRulesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MixedFieldRulesCreateBulk) SaveX(ctx context.Context) []*MixedFieldRules {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MixedFieldRulesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MixedFieldRulesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
