// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/mixedfieldrules"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// MixedFieldRulesUpdate is the builder for updating MixedFieldRules entities.
type MixedFieldRulesUpdate struct {
	config
	hooks    []Hook
	mutation *MixedFieldRulesMutation
}

// Where appends a list predicates to the MixedFieldRulesUpdate builder.
func (_u *MixedFieldRulesUpdate) Where(ps ...predicate.MixedFieldRules) *MixedFieldRulesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBoth sets the "both" field.
func (_u *MixedFieldRulesUpdate) SetBoth(v string) *MixedFieldRulesUpdate {
	_u.mutation.SetBoth(v)
	return _u
}

// SetNillableBoth sets the "both" field if the given value is not nil.
func (_u *MixedFieldRulesUpdate) SetNillableBoth(v *string) *MixedFieldRulesUpdate {
	if v != nil {
		_u.SetBoth(*v)
	}
	return _u
}

// SetStandardOnly sets the "standard_only" field.
func (_u *MixedFieldRulesUpdate) SetStandardOnly(v string) *MixedFieldRulesUpdate {
	_u.mutation.SetStandardOnly(v)
	return _u
}

// SetNillableStandardOnly sets the "standard_only" field if the given value is not nil.
func (_u *MixedFieldRulesUpdate) SetNillableStandardOnly(v *string) *MixedFieldRulesUpdate {
	if v != nil {
		_u.SetStandardOnly(*v)
	}
	return _u
}

// SetCelOnly sets the "cel_only" field.
func (_u *MixedFieldRulesUpdate) SetCelOnly(v string) *MixedFieldRulesUpdate {
	_u.mutation.SetCelOnly(v)
	return _u
}

// SetNillableCelOnly sets the "cel_only" field if the given value is not nil.
func (_u *MixedFieldRulesUpdate) SetNillableCelOnly(v *string) *MixedFieldRulesUpdate {
	if v != nil {
		_u.SetCelOnly(*v)
	}
	return _u
}

// Mutation returns the MixedFieldRulesMutation object of the builder.
func (_u *MixedFieldRulesUpdate) Mutation() *MixedFieldRulesMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MixedFieldRulesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MixedFieldRulesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MixedFieldRulesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MixedFieldRulesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MixedFieldRulesUpdate) check() error {
	if v, ok := _u.mutation.Both(); ok {
		if err := mixedfieldrules.BothValidator(v); err != nil {
			return &ValidationError{Name: "both", err: fmt.Errorf(`ent: validator failed for field "MixedFieldRules.both": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StandardOnly(); ok {
		if err := mixedfieldrules.StandardOnlyValidator(v); err != nil {
			return &ValidationError{Name: "standard_only", err: fmt.Errorf(`ent: validator failed for field "MixedFieldRules.standard_only": %w`, err)}
		}
	}
	return nil
}

func (_u *MixedFieldRulesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mixedfieldrules.Table, mixedfieldrules.Columns, sqlgraph.NewFieldSpec(mixedfieldrules.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Both(); ok {
		_spec.SetField(mixedfieldrules.FieldBoth, field.TypeString, value)
	}
	if value, ok := _u.mutation.StandardOnly(); ok {
		_spec.SetField(mixedfieldrules.FieldStandardOnly, field.TypeString, value)
	}
	if value, ok := _u.mutation.CelOnly(); ok {
		_spec.SetField(mixedfieldrules.FieldCelOnly, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mixedfieldrules.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MixedFieldRulesUpdateOne is the builder for updating a single MixedFieldRules entity.
type MixedFieldRulesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MixedFieldRulesMutation
}

// SetBoth sets the "both" field.
func (_u *MixedFieldRulesUpdateOne) SetBoth(v string) *MixedFieldRulesUpdateOne {
	_u.mutation.SetBoth(v)
	return _u
}

// SetNillableBoth sets the "both" field if the given value is not nil.
func (_u *MixedFieldRulesUpdateOne) SetNillableBoth(v *string) *MixedFieldRulesUpdateOne {
	if v != nil {
		_u.SetBoth(*v)
	}
	return _u
}

// SetStandardOnly sets the "standard_only" field.
func (_u *MixedFieldRulesUpdateOne) SetStandardOnly(v string) *MixedFieldRulesUpdateOne {
	_u.mutation.SetStandardOnly(v)
	return _u
}

// SetNillableStandardOnly sets the "standard_only" field if the given value is not nil.
func (_u *MixedFieldRulesUpdateOne) SetNillableStandardOnly(v *string) *MixedFieldRulesUpdateOne {
	if v != nil {
		_u.SetStandardOnly(*v)
	}
	return _u
}

// SetCelOnly sets the "cel_only" field.
func (_u *MixedFieldRulesUpdateOne) SetCelOnly(v string) *MixedFieldRulesUpdateOne {
	_u.mutation.SetCelOnly(v)
	return _u
}

// SetNillableCelOnly sets the "cel_only" field if the given value is not nil.
func (_u *MixedFieldRulesUpdateOne) SetNillableCelOnly(v *string) *MixedFieldRulesUpdateOne {
	if v != nil {
		_u.SetCelOnly(*v)
	}
	return _u
}

// Mutation returns the MixedFieldRulesMutation object of the builder.
func (_u *MixedFieldRulesUpdateOne) Mutation() *MixedFieldRulesMutation {
	return _u.mutation
}

// Where appends a list predicates to the MixedFieldRulesUpdate builder.
func (_u *MixedFieldRulesUpdateOne) Where(ps ...predicate.MixedFieldRules) *MixedFieldRulesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MixedFieldRulesUpdateOne) Select(field string, fields ...string) *MixedFieldRulesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MixedFieldRules entity.
func (_u *MixedFieldRulesUpdateOne) Save(ctx context.Context) (*MixedFieldRules, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MixedFieldRulesUpdateOne) SaveX(ctx context.Context) *MixedFieldRules {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MixedFieldRulesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MixedFieldRulesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MixedFieldRulesUpdateOne) check() error {
	if v, ok := _u.mutation.Both(); ok {
		if err := mixedfieldrules.BothValidator(v); err != nil {
			return &ValidationError{Name: "both", err: fmt.Errorf(`ent: validator failed for field "MixedFieldRules.both": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StandardOnly(); ok {
		if err := mixedfieldrules.StandardOnlyValidator(v); err != nil {
			return &ValidationError{Name: "standard_only", err: fmt.Errorf(`ent: validator failed for field "MixedFieldRules.standard_only": %w`, err)}
		}
	}
	return nil
}

func (_u *MixedFieldRulesUpdateOne) sqlSave(ctx context.Context) (_node *MixedFieldRules, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mixedfieldrules.Table, mixedfieldrules.Columns, sqlgraph.NewFieldSpec(mixedfieldrules.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MixedFieldRules.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mixedfieldrules.FieldID)
		for _, f := range fields {
			if !mixedfieldrules.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mixedfieldrules.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Both(); ok {
		_spec.SetField(mixedfieldrules.FieldBoth, field.TypeString, value)
	}
	if value, ok := _u.mutation.StandardOnly(); ok {
		_spec.SetField(mixedfieldrules.FieldStandardOnly, field.TypeString, value)
	}
	if value, ok := _u.mutation.CelOnly(); ok {
		_spec.SetField(mixedfieldrules.FieldCelOnly, field.TypeString, value)
	}
	_node = &MixedFieldRules{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mixedfieldrules.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
