// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/overriddenmixedfieldrules"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// OverriddenMixedFieldRulesDelete is the builder for deleting a OverriddenMixedFieldRules entity.
type OverriddenMixedFieldRulesDelete struct {
	config
	hooks    []Hook
	mutation *OverriddenMixedFieldRulesMutation
}

// Where appends a list predicates to the OverriddenMixedFieldRulesDelete builder.
func (_d *OverriddenMixedFieldRulesDelete) Where(ps ...predicate.OverriddenMixedFieldRules) *OverriddenMixedFieldRulesDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OverriddenMixedFieldRulesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OverriddenMixedFieldRulesDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OverriddenMixedFieldRulesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(overriddenmixedfieldrules.Table, sqlgraph.NewFieldSpec(overriddenmixedfieldrules.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OverriddenMixedFieldRulesDeleteOne is the builder for deleting a single OverriddenMixedFieldRules entity.
type OverriddenMixedFieldRulesDeleteOne struct {
	_d *OverriddenMixedFieldRulesDelete
}

// Where appends a list predicates to the OverriddenMixedFieldRulesDelete builder.
func (_d *OverriddenMixedFieldRulesDeleteOne) Where(ps ...predicate.OverriddenMixedFieldRules) *OverriddenMixedFieldRulesDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OverriddenMixedFieldRulesDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{overriddenmixedfieldrules.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OverriddenMixedFieldRulesDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
