// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/requiredoptionalbytes"
)

// RequiredOptionalBytesUpdate is the builder for updating RequiredOptionalBytes entities.
type RequiredOptionalBytesUpdate struct {
	config
	hooks    []Hook
	mutation *RequiredOptionalBytesMutation
}

// Where appends a list predicates to the RequiredOptionalBytesUpdate builder.
func (_u *RequiredOptionalBytesUpdate) Where(ps ...predicate.RequiredOptionalBytes) *RequiredOptionalBytesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValue sets the "value" field.
func (_u *RequiredOptionalBytesUpdate) SetValue(v []byte) *RequiredOptionalBytesUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// Mutation returns the RequiredOptionalBytesMutation object of the builder.
func (_u *RequiredOptionalBytesUpdate) Mutation() *RequiredOptionalBytesMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequiredOptionalBytesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequiredOptionalBytesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequiredOptionalBytesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequiredOptionalBytesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequiredOptionalBytesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(requiredoptionalbytes.Table, requiredoptionalbytes.Columns, sqlgraph.NewFieldSpec(requiredoptionalbytes.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(requiredoptionalbytes.FieldValue, field.TypeBytes, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requiredoptionalbytes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequiredOptionalBytesUpdateOne is the builder for updating a single RequiredOptionalBytes entity.
type RequiredOptionalBytesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequiredOptionalBytesMutation
}

// SetValue sets the "value" field.
func (_u *RequiredOptionalBytesUpdateOne) SetValue(v []byte) *RequiredOptionalBytesUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// Mutation returns the RequiredOptionalBytesMutation object of the builder.
func (_u *RequiredOptionalBytesUpdateOne) Mutation() *RequiredOptionalBytesMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequiredOptionalBytesUpdate builder.
func (_u *RequiredOptionalBytesUpdateOne) Where(ps ...predicate.RequiredOptionalBytes) *RequiredOptionalBytesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequiredOptionalBytesUpdateOne) Select(field string, fields ...string) *RequiredOptionalBytesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequiredOptionalBytes entity.
func (_u *RequiredOptionalBytesUpdateOne) Save(ctx context.Context) (*RequiredOptionalBytes, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequiredOptionalBytesUpdateOne) SaveX(ctx context.Context) *RequiredOptionalBytes {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequiredOptionalBytesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequiredOptionalBytesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequiredOptionalBytesUpdateOne) sqlSave(ctx context.Context) (_node *RequiredOptionalBytes, err error) {
	_spec := sqlgraph.NewUpdateSpec(requiredoptionalbytes.Table, requiredoptionalbytes.Columns, sqlgraph.NewFieldSpec(requiredoptionalbytes.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequiredOptionalBytes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requiredoptionalbytes.FieldID)
		for _, f := range fields {
			if !requiredoptionalbytes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requiredoptionalbytes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(requiredoptionalbytes.FieldValue, field.TypeBytes, value)
	}
	_node = &RequiredOptionalBytes{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requiredoptionalbytes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
