// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/requiredoptionalbytes"
)

// RequiredOptionalBytes is the model entity for the RequiredOptionalBytes schema.
type RequiredOptionalBytes struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Value holds the value of the "value" field.
	Value        []byte `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequiredOptionalBytes) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requiredoptionalbytes.FieldValue:
			values[i] = new([]byte)
		case requiredoptionalbytes.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequiredOptionalBytes fields.
func (_m *RequiredOptionalBytes) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requiredoptionalbytes.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case requiredoptionalbytes.FieldValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value != nil {
				_m.Value = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the RequiredOptionalBytes.
// This includes values selected through modifiers, order, etc.
func (_m *RequiredOptionalBytes) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RequiredOptionalBytes.
// Note that you need to call RequiredOptionalBytes.Unwrap() before calling this method if this RequiredOptionalBytes
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequiredOptionalBytes) Update() *RequiredOptionalBytesUpdateOne {
	return NewRequiredOptionalBytesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequiredOptionalBytes entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequiredOptionalBytes) Unwrap() *RequiredOptionalBytes {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequiredOptionalBytes is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequiredOptionalBytes) String() string {
	var builder strings.Builder
	builder.WriteString("RequiredOptionalBytes(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteByte(')')
	return builder.String()
}

// RequiredOptionalBytesSlice is a parsable slice of RequiredOptionalBytes.
type RequiredOptionalBytesSlice []*RequiredOptionalBytes
