// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/requiredstring"
)

// RequiredStringUpdate is the builder for updating RequiredString entities.
type RequiredStringUpdate struct {
	config
	hooks    []Hook
	mutation *RequiredStringMutation
}

// Where appends a list predicates to the RequiredStringUpdate builder.
func (_u *RequiredStringUpdate) Where(ps ...predicate.RequiredString) *RequiredStringUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValue sets the "value" field.
func (_u *RequiredStringUpdate) SetValue(v string) *RequiredStringUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *RequiredStringUpdate) SetNillableValue(v *string) *RequiredStringUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the RequiredStringMutation object of the builder.
func (_u *RequiredStringUpdate) Mutation() *RequiredStringMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequiredStringUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequiredStringUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequiredStringUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequiredStringUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequiredStringUpdate) check() error {
	if v, ok := _u.mutation.Value(); ok {
		if err := requiredstring.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "RequiredString.value": %w`, err)}
		}
	}
	return nil
}

func (_u *RequiredStringUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requiredstring.Table, requiredstring.Columns, sqlgraph.NewFieldSpec(requiredstring.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(requiredstring.FieldValue, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requiredstring.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequiredStringUpdateOne is the builder for updating a single RequiredString entity.
type RequiredStringUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequiredStringMutation
}

// SetValue sets the "value" field.
func (_u *RequiredStringUpdateOne) SetValue(v string) *RequiredStringUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *RequiredStringUpdateOne) SetNillableValue(v *string) *RequiredStringUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the RequiredStringMutation object of the builder.
func (_u *RequiredStringUpdateOne) Mutation() *RequiredStringMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequiredStringUpdate builder.
func (_u *RequiredStringUpdateOne) Where(ps ...predicate.RequiredString) *RequiredStringUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequiredStringUpdateOne) Select(field string, fields ...string) *RequiredStringUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequiredString entity.
func (_u *RequiredStringUpdateOne) Save(ctx context.Context) (*RequiredString, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequiredStringUpdateOne) SaveX(ctx context.Context) *RequiredString {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequiredStringUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequiredStringUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequiredStringUpdateOne) check() error {
	if v, ok := _u.mutation.Value(); ok {
		if err := requiredstring.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "RequiredString.value": %w`, err)}
		}
	}
	return nil
}

func (_u *RequiredStringUpdateOne) sqlSave(ctx context.Context) (_node *RequiredString, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requiredstring.Table, requiredstring.Columns, sqlgraph.NewFieldSpec(requiredstring.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequiredString.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requiredstring.FieldID)
		for _, f := range fields {
			if !requiredstring.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requiredstring.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(requiredstring.FieldValue, field.TypeString, value)
	}
	_node = &RequiredString{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requiredstring.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
