// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/requiredstring"
)

// RequiredStringCreate is the builder for creating a RequiredString entity.
type RequiredStringCreate struct {
	config
	mutation *RequiredStringMutation
	hooks    []Hook
}

// SetValue sets the "value" field.
func (_c *RequiredStringCreate) SetValue(v string) *RequiredStringCreate {
	_c.mutation.SetValue(v)
	return _c
}

// Mutation returns the RequiredStringMutation object of the builder.
func (_c *RequiredStringCreate) Mutation() *RequiredStringMutation {
	return _c.mutation
}

// Save creates the RequiredString in the database.
func (_c *RequiredStringCreate) Save(ctx context.Context) (*RequiredString, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequiredStringCreate) SaveX(ctx context.Context) *RequiredString {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequiredStringCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequiredStringCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequiredStringCreate) check() error {
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "RequiredString.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := requiredstring.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "RequiredString.value": %w`, err)}
		}
	}
	return nil
}

func (_c *RequiredStringCreate) sqlSave(ctx context.Context) (*RequiredString, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequiredStringCreate) createSpec() (*RequiredString, *sqlgraph.CreateSpec) {
	var (
		_node = &RequiredString{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requiredstring.Table, sqlgraph.NewFieldSpec(requiredstring.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(requiredstring.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// RequiredStringCreateBulk is the builder for creating many RequiredString entities in bulk.
type RequiredStringCreateBulk struct {
	config
	err      error
	builders []*RequiredStringCreate
}

// Save creates the RequiredString entities in the database.
func (_c *RequiredStringCreateBulk) Save(ctx context.Context) ([]*RequiredString, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequiredString, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequiredStringMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequiredStringCreateBulk) SaveX(ctx context.Context) []*RequiredString {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequiredStringCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequiredStringCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
