// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/requiredoptionalnonstring"
)

// RequiredOptionalNonStringUpdate is the builder for updating RequiredOptionalNonString entities.
type RequiredOptionalNonStringUpdate struct {
	config
	hooks    []Hook
	mutation *RequiredOptionalNonStringMutation
}

// Where appends a list predicates to the RequiredOptionalNonStringUpdate builder.
func (_u *RequiredOptionalNonStringUpdate) Where(ps ...predicate.RequiredOptionalNonString) *RequiredOptionalNonStringUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValue sets the "value" field.
func (_u *RequiredOptionalNonStringUpdate) SetValue(v int32) *RequiredOptionalNonStringUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *RequiredOptionalNonStringUpdate) SetNillableValue(v *int32) *RequiredOptionalNonStringUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *RequiredOptionalNonStringUpdate) AddValue(v int32) *RequiredOptionalNonStringUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// Mutation returns the RequiredOptionalNonStringMutation object of the builder.
func (_u *RequiredOptionalNonStringUpdate) Mutation() *RequiredOptionalNonStringMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequiredOptionalNonStringUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequiredOptionalNonStringUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequiredOptionalNonStringUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequiredOptionalNonStringUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequiredOptionalNonStringUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(requiredoptionalnonstring.Table, requiredoptionalnonstring.Columns, sqlgraph.NewFieldSpec(requiredoptionalnonstring.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(requiredoptionalnonstring.FieldValue, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(requiredoptionalnonstring.FieldValue, field.TypeInt32, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requiredoptionalnonstring.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequiredOptionalNonStringUpdateOne is the builder for updating a single RequiredOptionalNonString entity.
type RequiredOptionalNonStringUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequiredOptionalNonStringMutation
}

// SetValue sets the "value" field.
func (_u *RequiredOptionalNonStringUpdateOne) SetValue(v int32) *RequiredOptionalNonStringUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *RequiredOptionalNonStringUpdateOne) SetNillableValue(v *int32) *RequiredOptionalNonStringUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *RequiredOptionalNonStringUpdateOne) AddValue(v int32) *RequiredOptionalNonStringUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// Mutation returns the RequiredOptionalNonStringMutation object of the builder.
func (_u *RequiredOptionalNonStringUpdateOne) Mutation() *RequiredOptionalNonStringMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequiredOptionalNonStringUpdate builder.
func (_u *RequiredOptionalNonStringUpdateOne) Where(ps ...predicate.RequiredOptionalNonString) *RequiredOptionalNonStringUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequiredOptionalNonStringUpdateOne) Select(field string, fields ...string) *RequiredOptionalNonStringUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequiredOptionalNonString entity.
func (_u *RequiredOptionalNonStringUpdateOne) Save(ctx context.Context) (*RequiredOptionalNonString, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequiredOptionalNonStringUpdateOne) SaveX(ctx context.Context) *RequiredOptionalNonString {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequiredOptionalNonStringUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequiredOptionalNonStringUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequiredOptionalNonStringUpdateOne) sqlSave(ctx context.Context) (_node *RequiredOptionalNonString, err error) {
	_spec := sqlgraph.NewUpdateSpec(requiredoptionalnonstring.Table, requiredoptionalnonstring.Columns, sqlgraph.NewFieldSpec(requiredoptionalnonstring.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequiredOptionalNonString.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requiredoptionalnonstring.FieldID)
		for _, f := range fields {
			if !requiredoptionalnonstring.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requiredoptionalnonstring.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(requiredoptionalnonstring.FieldValue, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(requiredoptionalnonstring.FieldValue, field.TypeInt32, value)
	}
	_node = &RequiredOptionalNonString{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requiredoptionalnonstring.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
