// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/requiredoptionalstring"
)

// RequiredOptionalStringCreate is the builder for creating a RequiredOptionalString entity.
type RequiredOptionalStringCreate struct {
	config
	mutation *RequiredOptionalStringMutation
	hooks    []Hook
}

// SetValue sets the "value" field.
func (_c *RequiredOptionalStringCreate) SetValue(v string) *RequiredOptionalStringCreate {
	_c.mutation.SetValue(v)
	return _c
}

// Mutation returns the RequiredOptionalStringMutation object of the builder.
func (_c *RequiredOptionalStringCreate) Mutation() *RequiredOptionalStringMutation {
	return _c.mutation
}

// Save creates the RequiredOptionalString in the database.
func (_c *RequiredOptionalStringCreate) Save(ctx context.Context) (*RequiredOptionalString, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequiredOptionalStringCreate) SaveX(ctx context.Context) *RequiredOptionalString {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequiredOptionalStringCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequiredOptionalStringCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequiredOptionalStringCreate) check() error {
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "RequiredOptionalString.value"`)}
	}
	return nil
}

func (_c *RequiredOptionalStringCreate) sqlSave(ctx context.Context) (*RequiredOptionalString, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequiredOptionalStringCreate) createSpec() (*RequiredOptionalString, *sqlgraph.CreateSpec) {
	var (
		_node = &RequiredOptionalString{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requiredoptionalstring.Table, sqlgraph.NewFieldSpec(requiredoptionalstring.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(requiredoptionalstring.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// RequiredOptionalStringCreateBulk is the builder for creating many RequiredOptionalString entities in bulk.
type RequiredOptionalStringCreateBulk struct {
	config
	err      error
	builders []*RequiredOptionalStringCreate
}

// Save creates the RequiredOptionalString entities in the database.
func (_c *RequiredOptionalStringCreateBulk) Save(ctx context.Context) ([]*RequiredOptionalString, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequiredOptionalString, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequiredOptionalStringMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequiredOptionalStringCreateBulk) SaveX(ctx context.Context) []*RequiredOptionalString {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequiredOptionalStringCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequiredOptionalStringCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
