// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/stringformathostname"
)

// StringFormatHostnameUpdate is the builder for updating StringFormatHostname entities.
type StringFormatHostnameUpdate struct {
	config
	hooks    []Hook
	mutation *StringFormatHostnameMutation
}

// Where appends a list predicates to the StringFormatHostnameUpdate builder.
func (_u *StringFormatHostnameUpdate) Where(ps ...predicate.StringFormatHostname) *StringFormatHostnameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValue sets the "value" field.
func (_u *StringFormatHostnameUpdate) SetValue(v string) *StringFormatHostnameUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *StringFormatHostnameUpdate) SetNillableValue(v *string) *StringFormatHostnameUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the StringFormatHostnameMutation object of the builder.
func (_u *StringFormatHostnameUpdate) Mutation() *StringFormatHostnameMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StringFormatHostnameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StringFormatHostnameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StringFormatHostnameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StringFormatHostnameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StringFormatHostnameUpdate) check() error {
	if v, ok := _u.mutation.Value(); ok {
		if err := stringformathostname.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "StringFormatHostname.value": %w`, err)}
		}
	}
	return nil
}

func (_u *StringFormatHostnameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stringformathostname.Table, stringformathostname.Columns, sqlgraph.NewFieldSpec(stringformathostname.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(stringformathostname.FieldValue, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stringformathostname.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StringFormatHostnameUpdateOne is the builder for updating a single StringFormatHostname entity.
type StringFormatHostnameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StringFormatHostnameMutation
}

// SetValue sets the "value" field.
func (_u *StringFormatHostnameUpdateOne) SetValue(v string) *StringFormatHostnameUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *StringFormatHostnameUpdateOne) SetNillableValue(v *string) *StringFormatHostnameUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the StringFormatHostnameMutation object of the builder.
func (_u *StringFormatHostnameUpdateOne) Mutation() *StringFormatHostnameMutation {
	return _u.mutation
}

// Where appends a list predicates to the StringFormatHostnameUpdate builder.
func (_u *StringFormatHostnameUpdateOne) Where(ps ...predicate.StringFormatHostname) *StringFormatHostnameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StringFormatHostnameUpdateOne) Select(field string, fields ...string) *StringFormatHostnameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StringFormatHostname entity.
func (_u *StringFormatHostnameUpdateOne) Save(ctx context.Context) (*StringFormatHostname, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StringFormatHostnameUpdateOne) SaveX(ctx context.Context) *StringFormatHostname {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StringFormatHostnameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StringFormatHostnameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StringFormatHostnameUpdateOne) check() error {
	if v, ok := _u.mutation.Value(); ok {
		if err := stringformathostname.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "StringFormatHostname.value": %w`, err)}
		}
	}
	return nil
}

func (_u *StringFormatHostnameUpdateOne) sqlSave(ctx context.Context) (_node *StringFormatHostname, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stringformathostname.Table, stringformathostname.Columns, sqlgraph.NewFieldSpec(stringformathostname.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StringFormatHostname.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stringformathostname.FieldID)
		for _, f := range fields {
			if !stringformathostname.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stringformathostname.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(stringformathostname.FieldValue, field.TypeString, value)
	}
	_node = &StringFormatHostname{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stringformathostname.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
