// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/stringformatip"
)

// StringFormatIpCreate is the builder for creating a StringFormatIp entity.
type StringFormatIpCreate struct {
	config
	mutation *StringFormatIpMutation
	hooks    []Hook
}

// SetValue sets the "value" field.
func (_c *StringFormatIpCreate) SetValue(v string) *StringFormatIpCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *StringFormatIpCreate) SetNillableValue(v *string) *StringFormatIpCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// Mutation returns the StringFormatIpMutation object of the builder.
func (_c *StringFormatIpCreate) Mutation() *StringFormatIpMutation {
	return _c.mutation
}

// Save creates the StringFormatIp in the database.
func (_c *StringFormatIpCreate) Save(ctx context.Context) (*StringFormatIp, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StringFormatIpCreate) SaveX(ctx context.Context) *StringFormatIp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StringFormatIpCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StringFormatIpCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StringFormatIpCreate) defaults() error {
	if _, ok := _c.mutation.Value(); !ok {
		v := stringformatip.DefaultValue
		_c.mutation.SetValue(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *StringFormatIpCreate) check() error {
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "StringFormatIp.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := stringformatip.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "StringFormatIp.value": %w`, err)}
		}
	}
	return nil
}

func (_c *StringFormatIpCreate) sqlSave(ctx context.Context) (*StringFormatIp, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StringFormatIpCreate) createSpec() (*StringFormatIp, *sqlgraph.CreateSpec) {
	var (
		_node = &StringFormatIp{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(stringformatip.Table, sqlgraph.NewFieldSpec(stringformatip.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(stringformatip.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// StringFormatIpCreateBulk is the builder for creating many StringFormatIp entities in bulk.
type StringFormatIpCreateBulk struct {
	config
	err      error
	builders []*StringFormatIpCreate
}

// Save creates the StringFormatIp entities in the database.
func (_c *StringFormatIpCreateBulk) Save(ctx context.Context) ([]*StringFormatIp, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StringFormatIp, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StringFormatIpMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StringFormatIpCreateBulk) SaveX(ctx context.Context) []*StringFormatIp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StringFormatIpCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StringFormatIpCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
