// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/stringcodepointbounds"
)

// StringCodePointBoundsUpdate is the builder for updating StringCodePointBounds entities.
type StringCodePointBoundsUpdate struct {
	config
	hooks    []Hook
	mutation *StringCodePointBoundsMutation
}

// Where appends a list predicates to the StringCodePointBoundsUpdate builder.
func (_u *StringCodePointBoundsUpdate) Where(ps ...predicate.StringCodePointBounds) *StringCodePointBoundsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMinLenField sets the "min_len_field" field.
func (_u *StringCodePointBoundsUpdate) SetMinLenField(v string) *StringCodePointBoundsUpdate {
	_u.mutation.SetMinLenField(v)
	return _u
}

// SetNillableMinLenField sets the "min_len_field" field if the given value is not nil.
func (_u *StringCodePointBoundsUpdate) SetNillableMinLenField(v *string) *StringCodePointBoundsUpdate {
	if v != nil {
		_u.SetMinLenField(*v)
	}
	return _u
}

// SetMaxLenField sets the "max_len_field" field.
func (_u *StringCodePointBoundsUpdate) SetMaxLenField(v string) *StringCodePointBoundsUpdate {
	_u.mutation.SetMaxLenField(v)
	return _u
}

// SetNillableMaxLenField sets the "max_len_field" field if the given value is not nil.
func (_u *StringCodePointBoundsUpdate) SetNillableMaxLenField(v *string) *StringCodePointBoundsUpdate {
	if v != nil {
		_u.SetMaxLenField(*v)
	}
	return _u
}

// SetLenField sets the "len_field" field.
func (_u *StringCodePointBoundsUpdate) SetLenField(v string) *StringCodePointBoundsUpdate {
	_u.mutation.SetLenField(v)
	return _u
}

// SetNillableLenField sets the "len_field" field if the given value is not nil.
func (_u *StringCodePointBoundsUpdate) SetNillableLenField(v *string) *StringCodePointBoundsUpdate {
	if v != nil {
		_u.SetLenField(*v)
	}
	return _u
}

// Mutation returns the StringCodePointBoundsMutation object of the builder.
func (_u *StringCodePointBoundsUpdate) Mutation() *StringCodePointBoundsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StringCodePointBoundsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StringCodePointBoundsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StringCodePointBoundsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StringCodePointBoundsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StringCodePointBoundsUpdate) check() error {
	if v, ok := _u.mutation.MinLenField(); ok {
		if err := stringcodepointbounds.MinLenFieldValidator(v); err != nil {
			return &ValidationError{Name: "min_len_field", err: fmt.Errorf(`ent: validator failed for field "StringCodePointBounds.min_len_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxLenField(); ok {
		if err := stringcodepointbounds.MaxLenFieldValidator(v); err != nil {
			return &ValidationError{Name: "max_len_field", err: fmt.Errorf(`ent: validator failed for field "StringCodePointBounds.max_len_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LenField(); ok {
		if err := stringcodepointbounds.LenFieldValidator(v); err != nil {
			return &ValidationError{Name: "len_field", err: fmt.Errorf(`ent: validator failed for field "StringCodePointBounds.len_field": %w`, err)}
		}
	}
	return nil
}

func (_u *StringCodePointBoundsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stringcodepointbounds.Table, stringcodepointbounds.Columns, sqlgraph.NewFieldSpec(stringcodepointbounds.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MinLenField(); ok {
		_spec.SetField(stringcodepointbounds.FieldMinLenField, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxLenField(); ok {
		_spec.SetField(stringcodepointbounds.FieldMaxLenField, field.TypeString, value)
	}
	if value, ok := _u.mutation.LenField(); ok {
		_spec.SetField(stringcodepointbounds.FieldLenField, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stringcodepointbounds.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StringCodePointBoundsUpdateOne is the builder for updating a single StringCodePointBounds entity.
type StringCodePointBoundsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StringCodePointBoundsMutation
}

// SetMinLenField sets the "min_len_field" field.
func (_u *StringCodePointBoundsUpdateOne) SetMinLenField(v string) *StringCodePointBoundsUpdateOne {
	_u.mutation.SetMinLenField(v)
	return _u
}

// SetNillableMinLenField sets the "min_len_field" field if the given value is not nil.
func (_u *StringCodePointBoundsUpdateOne) SetNillableMinLenField(v *string) *StringCodePointBoundsUpdateOne {
	if v != nil {
		_u.SetMinLenField(*v)
	}
	return _u
}

// SetMaxLenField sets the "max_len_field" field.
func (_u *StringCodePointBoundsUpdateOne) SetMaxLenField(v string) *StringCodePointBoundsUpdateOne {
	_u.mutation.SetMaxLenField(v)
	return _u
}

// SetNillableMaxLenField sets the "max_len_field" field if the given value is not nil.
func (_u *StringCodePointBoundsUpdateOne) SetNillableMaxLenField(v *string) *StringCodePointBoundsUpdateOne {
	if v != nil {
		_u.SetMaxLenField(*v)
	}
	return _u
}

// SetLenField sets the "len_field" field.
func (_u *StringCodePointBoundsUpdateOne) SetLenField(v string) *StringCodePointBoundsUpdateOne {
	_u.mutation.SetLenField(v)
	return _u
}

// SetNillableLenField sets the "len_field" field if the given value is not nil.
func (_u *StringCodePointBoundsUpdateOne) SetNillableLenField(v *string) *StringCodePointBoundsUpdateOne {
	if v != nil {
		_u.SetLenField(*v)
	}
	return _u
}

// Mutation returns the StringCodePointBoundsMutation object of the builder.
func (_u *StringCodePointBoundsUpdateOne) Mutation() *StringCodePointBoundsMutation {
	return _u.mutation
}

// Where appends a list predicates to the StringCodePointBoundsUpdate builder.
func (_u *StringCodePointBoundsUpdateOne) Where(ps ...predicate.StringCodePointBounds) *StringCodePointBoundsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StringCodePointBoundsUpdateOne) Select(field string, fields ...string) *StringCodePointBoundsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StringCodePointBounds entity.
func (_u *StringCodePointBoundsUpdateOne) Save(ctx context.Context) (*StringCodePointBounds, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StringCodePointBoundsUpdateOne) SaveX(ctx context.Context) *StringCodePointBounds {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StringCodePointBoundsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StringCodePointBoundsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StringCodePointBoundsUpdateOne) check() error {
	if v, ok := _u.mutation.MinLenField(); ok {
		if err := stringcodepointbounds.MinLenFieldValidator(v); err != nil {
			return &ValidationError{Name: "min_len_field", err: fmt.Errorf(`ent: validator failed for field "StringCodePointBounds.min_len_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxLenField(); ok {
		if err := stringcodepointbounds.MaxLenFieldValidator(v); err != nil {
			return &ValidationError{Name: "max_len_field", err: fmt.Errorf(`ent: validator failed for field "StringCodePointBounds.max_len_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LenField(); ok {
		if err := stringcodepointbounds.LenFieldValidator(v); err != nil {
			return &ValidationError{Name: "len_field", err: fmt.Errorf(`ent: validator failed for field "StringCodePointBounds.len_field": %w`, err)}
		}
	}
	return nil
}

func (_u *StringCodePointBoundsUpdateOne) sqlSave(ctx context.Context) (_node *StringCodePointBounds, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stringcodepointbounds.Table, stringcodepointbounds.Columns, sqlgraph.NewFieldSpec(stringcodepointbounds.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StringCodePointBounds.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stringcodepointbounds.FieldID)
		for _, f := range fields {
			if !stringcodepointbounds.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stringcodepointbounds.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MinLenField(); ok {
		_spec.SetField(stringcodepointbounds.FieldMinLenField, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxLenField(); ok {
		_spec.SetField(stringcodepointbounds.FieldMaxLenField, field.TypeString, value)
	}
	if value, ok := _u.mutation.LenField(); ok {
		_spec.SetField(stringcodepointbounds.FieldLenField, field.TypeString, value)
	}
	_node = &StringCodePointBounds{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stringcodepointbounds.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
