// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/stringformatemail"
)

// StringFormatEmail is the model entity for the StringFormatEmail schema.
type StringFormatEmail struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Value holds the value of the "value" field.
	Value        string `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StringFormatEmail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stringformatemail.FieldID:
			values[i] = new(sql.NullInt64)
		case stringformatemail.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StringFormatEmail fields.
func (_m *StringFormatEmail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stringformatemail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case stringformatemail.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the StringFormatEmail.
// This includes values selected through modifiers, order, etc.
func (_m *StringFormatEmail) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StringFormatEmail.
// Note that you need to call StringFormatEmail.Unwrap() before calling this method if this StringFormatEmail
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StringFormatEmail) Update() *StringFormatEmailUpdateOne {
	return NewStringFormatEmailClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StringFormatEmail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StringFormatEmail) Unwrap() *StringFormatEmail {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StringFormatEmail is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StringFormatEmail) String() string {
	var builder strings.Builder
	builder.WriteString("StringFormatEmail(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteByte(')')
	return builder.String()
}

// StringFormatEmails is a parsable slice of StringFormatEmail.
type StringFormatEmails []*StringFormatEmail
