// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/stringformathostname"
)

// StringFormatHostnameCreate is the builder for creating a StringFormatHostname entity.
type StringFormatHostnameCreate struct {
	config
	mutation *StringFormatHostnameMutation
	hooks    []Hook
}

// SetValue sets the "value" field.
func (_c *StringFormatHostnameCreate) SetValue(v string) *StringFormatHostnameCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *StringFormatHostnameCreate) SetNillableValue(v *string) *StringFormatHostnameCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// Mutation returns the StringFormatHostnameMutation object of the builder.
func (_c *StringFormatHostnameCreate) Mutation() *StringFormatHostnameMutation {
	return _c.mutation
}

// Save creates the StringFormatHostname in the database.
func (_c *StringFormatHostnameCreate) Save(ctx context.Context) (*StringFormatHostname, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StringFormatHostnameCreate) SaveX(ctx context.Context) *StringFormatHostname {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StringFormatHostnameCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StringFormatHostnameCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StringFormatHostnameCreate) defaults() error {
	if _, ok := _c.mutation.Value(); !ok {
		v := stringformathostname.DefaultValue
		_c.mutation.SetValue(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *StringFormatHostnameCreate) check() error {
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "StringFormatHostname.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := stringformathostname.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "StringFormatHostname.value": %w`, err)}
		}
	}
	return nil
}

func (_c *StringFormatHostnameCreate) sqlSave(ctx context.Context) (*StringFormatHostname, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StringFormatHostnameCreate) createSpec() (*StringFormatHostname, *sqlgraph.CreateSpec) {
	var (
		_node = &StringFormatHostname{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(stringformathostname.Table, sqlgraph.NewFieldSpec(stringformathostname.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(stringformathostname.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// StringFormatHostnameCreateBulk is the builder for creating many StringFormatHostname entities in bulk.
type StringFormatHostnameCreateBulk struct {
	config
	err      error
	builders []*StringFormatHostnameCreate
}

// Save creates the StringFormatHostname entities in the database.
func (_c *StringFormatHostnameCreateBulk) Save(ctx context.Context) ([]*StringFormatHostname, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StringFormatHostname, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StringFormatHostnameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StringFormatHostnameCreateBulk) SaveX(ctx context.Context) []*StringFormatHostname {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StringFormatHostnameCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StringFormatHostnameCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
