// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/policed"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/schema"
	"github.com/smintz/entconnect/internal/entconnecttest/hookwiring/ent/unpoliced"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	policedMixin := schema.Policed{}.Mixin()
	policed.Policy = privacy.NewPolicies(schema.Policed{})
	policed.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := policed.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	policedMixinHooks0 := policedMixin[0].Hooks()
	policedHooks := schema.Policed{}.Hooks()

	policed.Hooks[1] = policedMixinHooks0[0]

	policed.Hooks[2] = policedHooks[0]
	policedMixinFields0 := policedMixin[0].Fields()
	_ = policedMixinFields0
	policedFields := schema.Policed{}.Fields()
	_ = policedFields
	// policedDescCelField is the schema descriptor for cel_field field.
	policedDescCelField := policedMixinFields0[0].Descriptor()
	// policed.DefaultCelField holds the default value on creation for the cel_field field.
	policed.DefaultCelField = policedDescCelField.Default.(string)
	// policedDescStandardField is the schema descriptor for standard_field field.
	policedDescStandardField := policedMixinFields0[1].Descriptor()
	// policed.DefaultStandardField holds the default value on creation for the standard_field field.
	policed.DefaultStandardField = policedDescStandardField.Default.(string)
	// policed.StandardFieldValidator is a validator for the "standard_field" field. It is called by the builders before save.
	policed.StandardFieldValidator = policedDescStandardField.Validators[0].(func(string) error)
	unpolicedMixin := schema.Unpoliced{}.Mixin()
	unpolicedMixinHooks0 := unpolicedMixin[0].Hooks()
	unpolicedHooks := schema.Unpoliced{}.Hooks()
	unpoliced.Hooks[0] = unpolicedMixinHooks0[0]
	unpoliced.Hooks[1] = unpolicedHooks[0]
	unpolicedMixinFields0 := unpolicedMixin[0].Fields()
	_ = unpolicedMixinFields0
	unpolicedFields := schema.Unpoliced{}.Fields()
	_ = unpolicedFields
	// unpolicedDescCelField is the schema descriptor for cel_field field.
	unpolicedDescCelField := unpolicedMixinFields0[0].Descriptor()
	// unpoliced.DefaultCelField holds the default value on creation for the cel_field field.
	unpoliced.DefaultCelField = unpolicedDescCelField.Default.(string)
	// unpolicedDescStandardField is the schema descriptor for standard_field field.
	unpolicedDescStandardField := unpolicedMixinFields0[1].Descriptor()
	// unpoliced.DefaultStandardField holds the default value on creation for the standard_field field.
	unpoliced.DefaultStandardField = unpolicedDescStandardField.Default.(string)
	// unpoliced.StandardFieldValidator is a validator for the "standard_field" field. It is called by the builders before save.
	unpoliced.StandardFieldValidator = unpolicedDescStandardField.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
