// Code generated by ent, DO NOT EDIT.

package mixedfieldrules

import (
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLTE(FieldID, id))
}

// Both applies equality check predicate on the "both" field. It's identical to BothEQ.
func Both(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldBoth, v))
}

// StandardOnly applies equality check predicate on the "standard_only" field. It's identical to StandardOnlyEQ.
func StandardOnly(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldStandardOnly, v))
}

// CelOnly applies equality check predicate on the "cel_only" field. It's identical to CelOnlyEQ.
func CelOnly(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldCelOnly, v))
}

// BothEQ applies the EQ predicate on the "both" field.
func BothEQ(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldBoth, v))
}

// BothNEQ applies the NEQ predicate on the "both" field.
func BothNEQ(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNEQ(FieldBoth, v))
}

// BothIn applies the In predicate on the "both" field.
func BothIn(vs ...string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldIn(FieldBoth, vs...))
}

// BothNotIn applies the NotIn predicate on the "both" field.
func BothNotIn(vs ...string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNotIn(FieldBoth, vs...))
}

// BothGT applies the GT predicate on the "both" field.
func BothGT(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGT(FieldBoth, v))
}

// BothGTE applies the GTE predicate on the "both" field.
func BothGTE(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGTE(FieldBoth, v))
}

// BothLT applies the LT predicate on the "both" field.
func BothLT(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLT(FieldBoth, v))
}

// BothLTE applies the LTE predicate on the "both" field.
func BothLTE(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLTE(FieldBoth, v))
}

// BothContains applies the Contains predicate on the "both" field.
func BothContains(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldContains(FieldBoth, v))
}

// BothHasPrefix applies the HasPrefix predicate on the "both" field.
func BothHasPrefix(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldHasPrefix(FieldBoth, v))
}

// BothHasSuffix applies the HasSuffix predicate on the "both" field.
func BothHasSuffix(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldHasSuffix(FieldBoth, v))
}

// BothEqualFold applies the EqualFold predicate on the "both" field.
func BothEqualFold(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEqualFold(FieldBoth, v))
}

// BothContainsFold applies the ContainsFold predicate on the "both" field.
func BothContainsFold(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldContainsFold(FieldBoth, v))
}

// StandardOnlyEQ applies the EQ predicate on the "standard_only" field.
func StandardOnlyEQ(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldStandardOnly, v))
}

// StandardOnlyNEQ applies the NEQ predicate on the "standard_only" field.
func StandardOnlyNEQ(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNEQ(FieldStandardOnly, v))
}

// StandardOnlyIn applies the In predicate on the "standard_only" field.
func StandardOnlyIn(vs ...string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldIn(FieldStandardOnly, vs...))
}

// StandardOnlyNotIn applies the NotIn predicate on the "standard_only" field.
func StandardOnlyNotIn(vs ...string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNotIn(FieldStandardOnly, vs...))
}

// StandardOnlyGT applies the GT predicate on the "standard_only" field.
func StandardOnlyGT(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGT(FieldStandardOnly, v))
}

// StandardOnlyGTE applies the GTE predicate on the "standard_only" field.
func StandardOnlyGTE(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGTE(FieldStandardOnly, v))
}

// StandardOnlyLT applies the LT predicate on the "standard_only" field.
func StandardOnlyLT(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLT(FieldStandardOnly, v))
}

// StandardOnlyLTE applies the LTE predicate on the "standard_only" field.
func StandardOnlyLTE(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLTE(FieldStandardOnly, v))
}

// StandardOnlyContains applies the Contains predicate on the "standard_only" field.
func StandardOnlyContains(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldContains(FieldStandardOnly, v))
}

// StandardOnlyHasPrefix applies the HasPrefix predicate on the "standard_only" field.
func StandardOnlyHasPrefix(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldHasPrefix(FieldStandardOnly, v))
}

// StandardOnlyHasSuffix applies the HasSuffix predicate on the "standard_only" field.
func StandardOnlyHasSuffix(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldHasSuffix(FieldStandardOnly, v))
}

// StandardOnlyEqualFold applies the EqualFold predicate on the "standard_only" field.
func StandardOnlyEqualFold(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEqualFold(FieldStandardOnly, v))
}

// StandardOnlyContainsFold applies the ContainsFold predicate on the "standard_only" field.
func StandardOnlyContainsFold(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldContainsFold(FieldStandardOnly, v))
}

// CelOnlyEQ applies the EQ predicate on the "cel_only" field.
func CelOnlyEQ(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEQ(FieldCelOnly, v))
}

// CelOnlyNEQ applies the NEQ predicate on the "cel_only" field.
func CelOnlyNEQ(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNEQ(FieldCelOnly, v))
}

// CelOnlyIn applies the In predicate on the "cel_only" field.
func CelOnlyIn(vs ...string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldIn(FieldCelOnly, vs...))
}

// CelOnlyNotIn applies the NotIn predicate on the "cel_only" field.
func CelOnlyNotIn(vs ...string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldNotIn(FieldCelOnly, vs...))
}

// CelOnlyGT applies the GT predicate on the "cel_only" field.
func CelOnlyGT(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGT(FieldCelOnly, v))
}

// CelOnlyGTE applies the GTE predicate on the "cel_only" field.
func CelOnlyGTE(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldGTE(FieldCelOnly, v))
}

// CelOnlyLT applies the LT predicate on the "cel_only" field.
func CelOnlyLT(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLT(FieldCelOnly, v))
}

// CelOnlyLTE applies the LTE predicate on the "cel_only" field.
func CelOnlyLTE(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldLTE(FieldCelOnly, v))
}

// CelOnlyContains applies the Contains predicate on the "cel_only" field.
func CelOnlyContains(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldContains(FieldCelOnly, v))
}

// CelOnlyHasPrefix applies the HasPrefix predicate on the "cel_only" field.
func CelOnlyHasPrefix(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldHasPrefix(FieldCelOnly, v))
}

// CelOnlyHasSuffix applies the HasSuffix predicate on the "cel_only" field.
func CelOnlyHasSuffix(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldHasSuffix(FieldCelOnly, v))
}

// CelOnlyEqualFold applies the EqualFold predicate on the "cel_only" field.
func CelOnlyEqualFold(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldEqualFold(FieldCelOnly, v))
}

// CelOnlyContainsFold applies the ContainsFold predicate on the "cel_only" field.
func CelOnlyContainsFold(v string) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.FieldContainsFold(FieldCelOnly, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MixedFieldRules) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MixedFieldRules) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MixedFieldRules) predicate.MixedFieldRules {
	return predicate.MixedFieldRules(sql.NotPredicates(p))
}
