// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/smintz/entconnect/internal/entconnecttest/write/ent/item"
	"github.com/smintz/entconnect/internal/entconnecttest/write/ent/schema"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemMixin := schema.Item{}.Mixin()
	item.Policy = privacy.NewPolicies(schema.Item{})
	item.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := item.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	itemMixinFields0 := itemMixin[0].Fields()
	_ = itemMixinFields0
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescSku is the schema descriptor for sku field.
	itemDescSku := itemMixinFields0[0].Descriptor()
	// item.DefaultSku holds the default value on creation for the sku field.
	item.DefaultSku = itemDescSku.Default.(string)
	// item.SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	item.SkuValidator = itemDescSku.Validators[0].(func(string) error)
	// itemDescName is the schema descriptor for name field.
	itemDescName := itemMixinFields0[1].Descriptor()
	// item.DefaultName holds the default value on creation for the name field.
	item.DefaultName = itemDescName.Default.(string)
	// itemDescQuantity is the schema descriptor for quantity field.
	itemDescQuantity := itemMixinFields0[2].Descriptor()
	// item.DefaultQuantity holds the default value on creation for the quantity field.
	item.DefaultQuantity = itemDescQuantity.Default.(int32)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
