// Code generated by ent, DO NOT EDIT.

package stringpattern

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the stringpattern type in the database.
	Label = "string_pattern"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValidPattern holds the string denoting the valid_pattern field in the database.
	FieldValidPattern = "valid_pattern"
	// Table holds the table name of the stringpattern in the database.
	Table = "string_patterns"
)

// Columns holds all SQL columns for stringpattern fields.
var Columns = []string{
	FieldID,
	FieldValidPattern,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/smintz/entconnect/mixinforproto/internal/difftest/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultValidPattern holds the default value on creation for the "valid_pattern" field.
	DefaultValidPattern string
	// ValidPatternValidator is a validator for the "valid_pattern" field. It is called by the builders before save.
	ValidPatternValidator func(string) error
)

// OrderOption defines the ordering options for the StringPattern queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByValidPattern orders the results by the valid_pattern field.
func ByValidPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidPattern, opts...).ToFunc()
}
