// Code generated by entconnect. DO NOT EDIT.

package entconnect

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"connectrpc.com/connect"
	"github.com/smintz/entconnect/internal/entconnecttest/list/ent"
	"github.com/smintz/entconnect/internal/entconnecttest/list/ent/page"
	"github.com/smintz/entconnect/internal/gen/entconnecttestv1"
	"github.com/smintz/entconnect/internal/gen/entconnecttestv1/entconnecttestv1connect"
	entconnectruntime "github.com/smintz/entconnect/runtime"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// pageListServiceServer implements entconnecttestv1connect.PageListServiceHandler
// against a real *ent.Client. Constructed only inside NewServer
// (server.entconnect.go, combining every service this graph binds) —
// application code never receives one directly, and this type exposes
// no accessor of any kind to the *ent.Client it holds (CRUD-07/D-12).
type pageListServiceServer struct {
	client *ent.Client
}

var _ entconnecttestv1connect.PageListServiceHandler = (*pageListServiceServer)(nil)

// ListPagesDefaultPageSize and ListPagesMaxPageSize are ListPages's page_size
// clamp bounds (T-02-13): page_size is clamped into [1, ListPagesMaxPageSize]
// with ListPagesDefaultPageSize applied when the request's page_size is zero or
// negative, so no query below can ever be unbounded.
const (
	ListPagesDefaultPageSize = 50
	ListPagesMaxPageSize     = 100
)

func (s *pageListServiceServer) ListPages(ctx context.Context, req *connect.Request[entconnecttestv1.ListPagesRequest]) (*connect.Response[entconnecttestv1.ListPagesResponse], error) {
	pageSize := int(req.Msg.GetPageSize())
	switch {
	case pageSize <= 0:
		pageSize = ListPagesDefaultPageSize
	case pageSize > ListPagesMaxPageSize:
		pageSize = ListPagesMaxPageSize
	}

	fingerprint := entconnectruntime.Fingerprint("CreatedAt", "ID")

	q := s.client.Page.Query().
		Order(page.ByCreatedAt(), page.ByID()).
		Limit(pageSize + 1)

	if token := req.Msg.GetPageToken(); token != "" {
		cursor, err := entconnectruntime.DecodeCursor(token, fingerprint)
		if err != nil {
			return nil, connect.NewError(connect.CodeInvalidArgument, err)
		}
		if len(cursor.Keys) != 2 {
			return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("page_token: want %d cursor keys, got %d", 2, len(cursor.Keys)))
		}

		keyCreatedAt, err := time.Parse(time.RFC3339Nano, cursor.Keys[0])
		if err != nil {
			return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("page_token: invalid CreatedAt: %w", err))
		}

		keyIDParsed, err := strconv.ParseInt(cursor.Keys[1], 10, 64)
		if err != nil {
			return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("page_token: invalid ID: %w", err))
		}
		keyID := int(keyIDParsed)

		q = q.Where(page.Or(
			page.CreatedAtGT(keyCreatedAt),
			page.And(
				page.CreatedAtEQ(keyCreatedAt),
				page.IDGT(keyID),
			),
		))
	}

	rows, err := q.All(ctx)
	if err != nil {
		return nil, entconnectruntime.MapError(err)
	}

	hasNext := len(rows) > pageSize
	if hasNext {
		rows = rows[:pageSize]
	}

	resp := &entconnecttestv1.ListPagesResponse{
		Pages: make([]*entconnecttestv1.Page, 0, len(rows)),
	}
	for _, row := range rows {
		resp.Pages = append(resp.Pages, &entconnecttestv1.Page{
			Id:        fmt.Sprint(row.ID),
			Title:     row.Title,
			CreatedAt: timestamppb.New(row.CreatedAt),
		})
	}
	if hasNext {
		last := rows[len(rows)-1]
		resp.NextPageToken = entconnectruntime.EncodeCursor(fingerprint, last.CreatedAt.Format(time.RFC3339Nano), strconv.FormatInt(int64(last.ID), 10))
	}

	return connect.NewResponse(resp), nil
}
