// Code generated by entconnect. DO NOT EDIT.

package entconnect

import (
	"github.com/smintz/entconnect/internal/entconnecttest/list/ent"
	"github.com/smintz/entconnect/internal/gen/entconnecttestv1/entconnecttestv1connect"
	entconnectruntime "github.com/smintz/entconnect/runtime"
)

// NewServer builds the generated wiring for every RPC this graph's
// schemas bind (across every proto service touched, not just one): it
// constructs each *ent.Client-backed handler, wraps every one of them in
// the SAME fixed authn -> viewer injection -> protovalidate -> otel
// interceptor chain (INT-01, built once via entconnectruntime.Chain —
// D-13), and returns a single *entconnectruntime.Server exposing only
// Connect paths and http.Handlers across every bound service.
// Application code receives this return value, never the *ent.Client
// passed in.
func NewServer(client *ent.Client, authenticator entconnectruntime.Authenticator, opts ...entconnectruntime.Option) (*entconnectruntime.Server, error) {
	chain, err := entconnectruntime.Chain(authenticator, opts...)
	if err != nil {
		return nil, err
	}
	var routes []entconnectruntime.Route

	svc0 := &pageListServiceServer{client: client}
	path0, handler0 := entconnecttestv1connect.NewPageListServiceHandler(svc0, chain)
	routes = append(routes, entconnectruntime.Route{Path: path0, Handler: handler0})

	return entconnectruntime.NewServer(routes...), nil
}
